const DEFAULT_DATA = {
    races: [
        { id: 'race_human', name: 'Humano', description: 'Ganha uma Vantagem Bônus Gratuita (Rank: Novato).' },
        { id: 'race_dwarf', name: 'Anão', description: 'Visão no Escuro (Ignora penalidade Escuridão). Lento (Mov. 5, corrida d4). Robusto (Vigor d6).' },
        { id: 'race_elf', name: 'Elfo', description: 'Agilidade d6. Visão na Penumbra. Desajeitado (com tecnologia moderna).' },
        { id: 'race_halfelf', name: 'Meio-Elfo', description: 'Visão na Penumbra. Ignora Herança com humanos/elfos. +1 Ponto Híbrido livre.' },
        { id: 'race_rakashan', name: 'Rakashano', description: 'Agilidade d6. Arma Natural (For+d4). Visão na Penumbra. Animalesco. Curioso.' },
        { id: 'race_saurian', name: 'Sauriano', description: 'Visão no Escuro. Vigor d6. Pele Dura (+2 Armadura Nat.). Termossensível. Animalesco.' },
        { id: 'race_android', name: 'Androide', description: 'Astúcia d6. Construto (+2 Rec., Imune a Veneno/Fadiga). Inábil Socialmente (Sem Noção).' },
        { id: 'race_atlantean', name: 'Atlante', description: 'Anfíbio. Vigor d6. Desidratação (-1 Fadiga caso 24h sem água).' }
    ],
    attributes: [
        { id: 'attr_agility', name: 'Agilidade' }, { id: 'attr_smarts', name: 'Astúcia' },
        { id: 'attr_spirit', name: 'Espírito' }, { id: 'attr_strength', name: 'Força' },
        { id: 'attr_vigor', name: 'Vigor' }
    ],
    skills: [
        // CORE
        { id: 'skill_athletics', name: 'Atletismo', linked: 'Agilidade', isCore: true },
        { id: 'skill_common_knowledge', name: 'Conhecimento Geral', linked: 'Astúcia', isCore: true },
        { id: 'skill_notice', name: 'Perceber', linked: 'Astúcia', isCore: true },
        { id: 'skill_persuasion', name: 'Persuasão', linked: 'Espírito', isCore: true },
        { id: 'skill_stealth', name: 'Furtividade', linked: 'Agilidade', isCore: true },
        // EXTENDIDAS
        { id: 'skill_shooting', name: 'Atirar', linked: 'Agilidade', isCore: false },
        { id: 'skill_riding', name: 'Cavalgar', linked: 'Agilidade', isCore: false },
        { id: 'skill_academics', name: 'Acadêmicos', linked: 'Astúcia', isCore: false },
        { id: 'skill_battle', name: 'Batalha', linked: 'Astúcia', isCore: false },
        { id: 'skill_science', name: 'Ciência', linked: 'Astúcia', isCore: false },
        { id: 'skill_repair', name: 'Consertar', linked: 'Astúcia', isCore: false },
        { id: 'skill_healing', name: 'Curar', linked: 'Astúcia', isCore: false },
        { id: 'skill_driving', name: 'Dirigir', linked: 'Agilidade', isCore: false },
        { id: 'skill_electronics', name: 'Eletrônicos', linked: 'Astúcia', isCore: false },
        { id: 'skill_focus', name: 'Foco', linked: 'Espírito', isCore: false },
        { id: 'skill_thievery', name: 'Crime / Furto', linked: 'Agilidade', isCore: false },
        { id: 'skill_hacking', name: 'Hackear', linked: 'Astúcia', isCore: false },
        { id: 'skill_language', name: 'Idiomas', linked: 'Astúcia', isCore: false },
        { id: 'skill_intimidation', name: 'Intimidar', linked: 'Espírito', isCore: false },
        { id: 'skill_gambling', name: 'Jogar', linked: 'Astúcia', isCore: false },
        { id: 'skill_fighting', name: 'Lutar', linked: 'Agilidade', isCore: false },
        { id: 'skill_magic', name: 'Arcano / Fé', linked: 'Astúcia', isCore: false },
        { id: 'skill_boating', name: 'Navegar', linked: 'Agilidade', isCore: false },
        { id: 'skill_occult', name: 'Ocultismo', linked: 'Astúcia', isCore: false },
        { id: 'skill_operate', name: 'Operar (Máquinas)', linked: 'Agilidade', isCore: false },
        { id: 'skill_performance', name: 'Performance', linked: 'Espírito', isCore: false },
        { id: 'skill_piloting', name: 'Pilotar', linked: 'Agilidade', isCore: false },
        { id: 'skill_taunt', name: 'Provocar', linked: 'Astúcia', isCore: false },
        { id: 'skill_survival', name: 'Sobrevivência', linked: 'Astúcia', isCore: false }
    ],
    hindrances: [
        { id: 'hind_almofadinha', name: 'Almofadinha', type: 'Menor', description: 'O herói não parece ameaçador. Subtrai 2 de rolagens de Intimidar.', effects: { intimidate: -2 } },
        { id: 'hind_analfabeto', name: 'Analfabeto', type: 'Menor', description: 'Não sabe ler ou escrever.' },
        { id: 'hind_anemico', name: 'Anêmico', type: 'Menor', description: '-2 em Vigor para resistir a Fadiga.', effects: { vigor_fatigue: -2 } },
        { id: 'hind_arrogante', name: 'Arrogante', type: 'Maior', description: 'Quer dominar e sempre busca o oponente mais forte.' },
        { id: 'hind_atrapalhado', name: 'Atrapalhado', type: 'Maior', description: '-2 em Atletismo e Furtividade.', effects: { athletics: -2, stealth: -2 } },
        { id: 'hind_bocagrande', name: 'Boca Grande', type: 'Menor', description: 'Não sabe guardar segredos.' },
        { id: 'hind_cauteloso', name: 'Cauteloso', type: 'Menor', description: 'Planeja demais, nunca toma decisões precipitadas.' },
        { id: 'hind_cego', name: 'Cego', type: 'Maior', description: '-6 em tarefas visuais. Ganha +1 Vantagem adicional grátis.', effects: { vision: -6, free_edges: 1 } },
        { id: 'hind_codigo', name: 'Código de Honra', type: 'Maior', description: 'Mantém a palavra e nunca abusa de prisioneiros.' },
        { id: 'hind_covarde', name: 'Covarde', type: 'Maior', description: '-2 rolagens de Medo e para resistir a Intimidar.', effects: { fear: -2, resist_intimidation: -2 } },
        { id: 'hind_curioso', name: 'Curioso', type: 'Maior', description: 'Precisa checar qualquer mistério.' },
        { id: 'hind_def_auditivo', name: 'Deficiente Auditivo', type: 'Menor/Maior', description: 'Menor: -4 em Perceber (áudio). Maior: Falha automática.', effects: { notice_hearing: -4 } },
        { id: 'hind_delirante', name: 'Delirante', type: 'Menor/Maior', description: 'Acredita em algo estranho ou fatal.' },
        { id: 'hind_desagradavel', name: 'Desagradável', type: 'Menor', description: 'Mal-humorado. -1 nas rolagens de Persuadir.', effects: { persuasion: -1 } },
        { id: 'hind_desastrado', name: 'Desastrado', type: 'Menor', description: '-2 ao usar dispositivos elétricos ou mecânicos.', effects: { mechanical: -2 } },
        { id: 'hind_desconfiado', name: 'Desconfiado', type: 'Menor/Maior', description: 'Paranoico. Maior: -2 em testes de Suporte lançados sobre ele.' },
        { id: 'hind_desejo_morrer', name: 'Desejo de Morrer', type: 'Menor', description: 'Acha sua vida menos valiosa que seu nobre objetivo.' },
        { id: 'hind_excesso_conf', name: 'Excesso de Confiança', type: 'Maior', description: 'Acha que pode derrotar qualquer coisa.' },
        { id: 'hind_feio', name: 'Feio', type: 'Menor/Maior', description: 'Aparência deplorável. Subtrai 1 ou 2 de rolagens de Persuadir.', effects: { persuasion: -1 } },
        { id: 'hind_fobia', name: 'Fobia', type: 'Menor/Maior', description: 'Medo esmagador que causa penalidade de -1 ou -2 perto do gatilho.', effects: { phobia_penalty: -1 } },
        { id: 'hind_forasteiro', name: 'Forasteiro', type: 'Menor/Maior', description: 'Descriminado localmente. -2 Persuadir com locais.', effects: { persuasion: -2 } },
        { id: 'hind_ganancioso', name: 'Ganancioso', type: 'Menor/Maior', description: 'Obcecado por riquezas.' },
        { id: 'hind_guiado', name: 'Guiado', type: 'Menor/Maior', description: 'Possui uma missão particular suprema.' },
        { id: 'hind_habito', name: 'Hábito', type: 'Menor/Maior', description: 'Vício ou mania nociva (Fadiga em caso de abstinência na Maior).' },
        { id: 'hind_heroico', name: 'Heroico', type: 'Maior', description: 'Sempre ajuda os necessitados livremente.' },
        { id: 'hind_hesitante', name: 'Hesitante', type: 'Menor', description: 'Puxa e age com a pior Carta de Ação no combate.' },
        { id: 'hind_idoso', name: 'Idoso', type: 'Maior', description: '-1 de Mov e Corrida, -1 For, Agi, Vig. Ganha 5pts para Astúcia.', effects: { pace: -1, run: -1, idoso_smarts: 5, attr_penalty: -1 } },
        { id: 'hind_impulsivo', name: 'Impulsivo', type: 'Maior', description: 'Mergulha de cabeça antes de pensar.' },
        { id: 'hind_incredulo', name: 'Incrédulo', type: 'Menor', description: 'Duvida e racionaliza o sobrenatural.' },
        { id: 'hind_inimigo', name: 'Inimigo', type: 'Menor/Maior', description: 'Alguém está te caçando ativamente.' },
        { id: 'hind_invejoso', name: 'Invejoso', type: 'Menor/Maior', description: 'Cobiça excessiva aos feitos ou itens alheios.' },
        { id: 'hind_jovem', name: 'Jovem', type: 'Menor/Maior', description: 'Menor (Atributos=4, Perícias=10, +1 Bene). Maior (Atr=3, +2 Ben, Tamanho-1).', effects: { jovem: true } },
        { id: 'hind_leal', name: 'Leal', type: 'Menor', description: 'Nunca arrisca não ajudar um aliado.' },
        { id: 'hind_lento', name: 'Lento', type: 'Menor/Maior', description: 'Menor: -1 Mov, -1 Corrida. Maior: -2 Mov, -2 Atletismo de locomoção.', effects: { pace: -1 } },
        { id: 'hind_lingua_presa', name: 'Língua Presa', type: 'Maior', description: '-1 Intimidar, Performance, Persuadir, e Provocar (verbal).', effects: { verbal: -1 } },
        { id: 'hind_ma_sorte', name: 'Má Sorte', type: 'Maior', description: 'Começa o jogo com um Bene a menos.', effects: { bennies: -1 } },
        { id: 'hind_mudo', name: 'Mudo', type: 'Maior', description: 'Não fala nada.' },
        { id: 'hind_nadador_ruim', name: 'Não Sabe Nadar', type: 'Menor', description: '-2 ao Nadar, andar na água custa 3 quadros.', effects: { swim: -2 } },
        { id: 'hind_obeso', name: 'Obeso', type: 'Menor', description: '+1 Tamanho e Resistência. -1 Mov e Corrida max.', effects: { size: 1, toughness: 1, pace: -1, run_die: -1 } },
        { id: 'hind_obrigacao', name: 'Obrigação', type: 'Menor/Maior', description: 'Consumo de 20 (Menor) a 40 (Maior) horas semanais trabalhando.' },
        { id: 'hind_pacifista', name: 'Pacifista', type: 'Menor/Maior', description: 'Luta contra a violência e poupa os fracos.' },
        { id: 'hind_peculiaridade', name: 'Peculiaridade', type: 'Menor', description: 'Traço cômico mas prejudicial de comportamento.' },
        { id: 'hind_pequeno', name: 'Pequeno', type: 'Menor', description: 'Tamanho e Resistência -1.', effects: { size: -1, toughness: -1 } },
        { id: 'hind_pobreza', name: 'Pobreza', type: 'Menor', description: 'Inicia e mantém os fundos cortados pela metade.', effects: { poverty: true } },
        { id: 'hind_procurado', name: 'Procurado', type: 'Menor/Maior', description: 'É procurado pela lei.' },
        { id: 'hind_sanguinario', name: 'Sanguinário', type: 'Maior', description: 'Nunca faz prisioneiros; retalia brutalmente.' },
        { id: 'hind_segredo', name: 'Segredo', type: 'Menor/Maior', description: 'Pode ser arruinado se revelarem sua mentira.' },
        { id: 'hind_sem_escrupulos', name: 'Sem Escrúpulos', type: 'Menor/Maior', description: 'Passará por cima de outros para um fim.' },
        { id: 'hind_sem_nocao', name: 'Sem Noção', type: 'Maior', description: 'Avistador ruim. -1 Perceber e Conhecimentos Gerais.', effects: { notice: -1, common_knowledge: -1 } },
        { id: 'hind_sensivel', name: 'Sensível', type: 'Menor/Maior', description: '-2 ou -4 para resistir a Provocar.', effects: { resist_taunt: -2 } },
        { id: 'hind_teimoso', name: 'Teimoso', type: 'Menor', description: 'Sempre tenta mandar.' },
        { id: 'hind_um_braco', name: 'Um Braço Só', type: 'Maior', description: '-4 em ações que requiram duas mãos.', effects: { two_handed: -4 } },
        { id: 'hind_um_olho', name: 'Um Olho Só', type: 'Maior', description: '-2 visão além de 10 metros.', effects: { vision_range: -2 } },
        { id: 'hind_vergonha', name: 'Vergonha', type: 'Menor/Maior', description: 'Reputação secreta ou declarada vergonhosa.' },
        { id: 'hind_vingativo', name: 'Vingativo', type: 'Menor/Maior', description: 'Jamais deixa um desaforo por isso mesmo.' },
        { id: 'hind_visao_ruim', name: 'Visão Ruim', type: 'Menor/Maior', description: '-1 ou -2 em testes de visão caso sem óculos.', effects: { vision: -1 } },
        { id: 'hind_voto', name: 'Voto', type: 'Menor/Maior', description: 'Juramento sagrado que gasta seu tempo diário.' }
    ],
    edges: [
        // --- ANTECEDENTES ---
        { id: 'edge_bg_alertness', type: 'Antecedentes', name: 'Prontidão', requirements: 'Novato', description: '+2 nas rolagens de Perceber para ouvir ver ou sentir o mundo ao redor.', effects: { notice: 2 } },
        { id: 'edge_bg_ambidextrous', type: 'Antecedentes', name: 'Ambidestro', requirements: 'Novato, Agilidade d8+', description: 'Ignora a penalidade de -2 por usar a mão inábil em ataques e ações.' },
        { id: 'edge_bg_arcanebg', type: 'Antecedentes', name: 'Antecedente Arcano', requirements: 'Novato', description: 'Permite o uso de Magias. Requer escolha do contexto de poder.', requireInput: 'arcane_type', arcaneTypes: [
            { id: 'arc_gift', name: 'Dom', pp: 15, powers: 1, skill: 'Foco (Espírito)', desc: 'Poderes e efeitos inatos (superpoderes latentes), que não cabem direito nos padrões mágicos ou milagrosos.' },
            { id: 'arc_magic', name: 'Magia', pp: 10, powers: 3, skill: 'Conjurar (Astúcia)', desc: 'Magos, feiticeiros e cultistas extraindo energia mística de gestos e grimórios seculares.' },
            { id: 'arc_miracles', name: 'Milagres', pp: 10, powers: 3, skill: 'Fé (Espírito)', desc: 'Invocações de natureza divina, como curas e aflições.' },
            { id: 'arc_psionics', name: 'Psiônicos', pp: 10, powers: 3, skill: 'Psiônicos (Astúcia)', desc: 'Controle da matéria e entropia puramente pela própria energia mental/cérebro.' },
            { id: 'arc_weirdsci', name: 'Ciência Estranha', pp: 15, powers: 2, skill: 'Ciência Estranha (Astúcia)', desc: 'Alquimistas e inventores criadores de engenhocas e tecnologias bizarras/steampunk.' }
        ]},
        { id: 'edge_bg_aristocrat', type: 'Antecedentes', name: 'Aristocrata', requirements: 'Novato', description: '+2 nas rolagens de Persuasão com figuras da Riqueza e Nobreza.' },
        { id: 'edge_bg_attractive', type: 'Antecedentes', name: 'Atraente', requirements: 'Novato, Vigor d6+', description: '+1 em Persuasão e Performance nos que sentem atração pelo herói.' },
        { id: 'edge_bg_veryattractive', type: 'Antecedentes', name: 'Muito Atraente', requirements: 'Novato, Atraente', description: '+2 em Persuasão e Performance nos que sentem atração pelo herói.' },
        { id: 'edge_bg_berserk', type: 'Antecedentes', name: 'Berserk', requirements: 'Novato', description: 'Ao sofrer Dano/Abalo: Luta+1, Força +d6, Resistência +2. Quando termina, fica Vulnerável e Fatigado.' },
        { id: 'edge_bg_brawn', type: 'Antecedentes', name: 'Brutamontes', requirements: 'Novato, Força d6+, Vigor d6+', description: 'Tamanho +1. Aumenta os limites físicos e a Resistência máxima em +1.', effects: { size: 1, toughness: 1 } },
        { id: 'edge_bg_fasthealer', type: 'Antecedentes', name: 'Curandeiro Rápido', requirements: 'Novato, Vigor d8+', description: '+2 em todas as rolagens de Vigor para Cura natural.', effects: { natural_healing: 2 } },
        { id: 'edge_bg_fleetfoot', type: 'Antecedentes', name: 'Ligeiro', requirements: 'Novato, Agilidade d6+', description: 'Movimentação +2. Usa d10 para correr em vez de d6.', effects: { pace: 2, run_die: 10 } },
        { id: 'edge_bg_lucky', type: 'Antecedentes', name: 'Sorte', requirements: 'Novato', description: '+1 Bene adicional no começo de cada sessão de jogo.', effects: { bennies: 1 } },
        { id: 'edge_bg_greatluck', type: 'Antecedentes', name: 'Sorte Grande', requirements: 'Novato, Sorte', description: '+2 Benes adicionais no começo de cada sessão de jogo (substitui Sorte).', effects: { bennies: 2 } },
        { id: 'edge_bg_rich', type: 'Antecedentes', name: 'Rico', requirements: 'Novato', description: 'O personagem inicia a campanha com fundos iniciais triplicados ($1500) e proventos anuais.', effects: { bought_funds: 2 } },
        { id: 'edge_bg_filthyrich', type: 'Antecedentes', name: 'Podre de Rico', requirements: 'Novato, Rico', description: 'O personagem possui 10x mais dinheiro inicial ($5000) e status de extrema riqueza.', effects: { bought_funds: 9 } },
        { id: 'edge_bg_brave', type: 'Antecedentes', name: 'Bravo', requirements: 'Novato, Espírito d6+', description: '+2 em testes de Medo e recuperações por efeitos de choque.' },

        // --- COMBATE ---
        { id: 'edge_cbt_acrobat', type: 'Combate', name: 'Acrobata', requirements: 'Novato, Agilidade d8+, Atletismo d8+', description: 'Rerrola testes de Atletismo e ganha +1 de Aparar passivo se não Estorvado.', effects: { parry: 1 } },
        { id: 'edge_cbt_assassin', type: 'Combate', name: 'Assassino', requirements: 'Novato, Agilidade d8+, Furtividade d8+', description: '+2 no Dano em oponentes Surpresos. Assassinos matam furtivamente.' },
        { id: 'edge_cbt_brawler', type: 'Combate', name: 'Briguento', requirements: 'Novato, Força d8+, Vigor d8+', description: 'Ganha +1 de Resistência pura e Golpes Desarmados batem For+d4 ao invés de d4.', effects: { toughness: 1 } },
        { id: 'edge_cbt_bruiser', type: 'Combate', name: 'Pugilista', requirements: 'Experiente, Briguento', description: 'Ganha outro +1 de Resistência (total +2). Golpes Desarmados batem For+d6.', effects: { toughness: 2 } },
        { id: 'edge_cbt_martialarts', type: 'Combate', name: 'Artista Marcial', requirements: 'Novato, Lutar d6+', description: 'Ataques Desarmados não são considerados armas improvisadas (+1 Dano) e são Letais (Arma Natural).' },
        { id: 'edge_cbt_block', type: 'Combate', name: 'Bloquear', requirements: 'Experiente, Lutar d8+', description: '+1 passivo em Aparar contra ataques corpo-a-corpo.', effects: { parry: 1 } },
        { id: 'edge_cbt_imp_block', type: 'Combate', name: 'Bloquear Aprimorado', requirements: 'Veterano, Bloquear', description: '+2 passivo em Aparar (substitui Bloquear).', effects: { parry: 2 } },
        { id: 'edge_cbt_dodge', type: 'Combate', name: 'Esquiva', requirements: 'Experiente, Agilidade d8+', description: 'Ataques à Distância contra você sofrem -1. Se Evadir ataques em área, ganha +1 no teste.' },
        { id: 'edge_cbt_imp_dodge', type: 'Combate', name: 'Esquiva Aprimorada', requirements: 'Veterano, Esquiva', description: 'Ataques à Distância sofrem -2. Se Evadir ataques em área, ganha +2 no teste.' },
        { id: 'edge_cbt_firststrike', type: 'Combate', name: 'Ataque Primeiro', requirements: 'Novato, Agilidade d8+', description: 'Ganha um (1) Ataque Livre por turno contra qualquer Inimigo que avance até alcance adjacente.' },
        { id: 'edge_cbt_imp_firstst', type: 'Combate', name: 'Ataque Primeiro Aprimorado', requirements: 'Heróico, Ataque Primeiro', description: 'Ataques Livres ilimitados (um por alvo) que avançar corpo a corpo.' },
        { id: 'edge_cbt_trademarkwep', type: 'Combate', name: 'Arma de Assinatura', requirements: 'Novato, Habilidade c/ Arma d8+', description: '+1 rolagens de ataque (Atirar, Coro-a-corpo e Atletismo[arremesso]) ou +1 Aparar usando-a defender.' },
        { id: 'edge_cbt_imp_tradewep', type: 'Combate', name: 'Arma de Assinatura Aprimorada', requirements: 'Experiente, Arma Assinatura', description: '+2 ataques baseados na arma e +2 no Aparar passivo feito pela arma.' },
        { id: 'edge_cbt_steadyhands', type: 'Combate', name: 'Mãos Firmes', requirements: 'Novato, Agilidade d8+', description: 'Personagem ignora Plataforma Instável e reduz penalidade de Corrida em -1.' },
        { id: 'edge_cbt_marksman', type: 'Combate', name: 'Atirador de Elite', requirements: 'Experiente, Atirar d8+', description: 'Se o personagem não se Move e não tem CdT >1, ignora ate 2 pontos de Penalidade a distância ou ganha +1.' },
        { id: 'edge_cbt_sniper', type: 'Combate', name: 'Sniper (Atirador Tático)', requirements: 'Heroico, Atirador de Elite', description: 'Sempre que usa a Ação Mirar com sucesso, seu Dano dispara aumentando por 1d6 extra.' },
        { id: 'edge_cbt_ironjaw', type: 'Combate', name: 'Mandíbula de Ferro', requirements: 'Novato, Vigor d8+', description: '+2 nas rolagens inatas de Absorver Dano para resistir aos Ferimentos pós-ataque.', effects: { soak: 2 } },
        { id: 'edge_cbt_sweep', type: 'Combate', name: 'Rasteira / Giro', requirements: 'Novato, Força d8+, Lutar d8+', description: 'Uma só rolagem de Lutar (com pen -2) atinge TODOS os alvos adjacentes (no seu Alcance).' },
        { id: 'edge_cbt_imp_sweep', type: 'Combate', name: 'Rasteira Aprimorada', requirements: 'Veterano, Rasteira', description: 'O ataque atingindo todos ignora a penalidade de -2. Acerta normalmente todos.' },
        { id: 'edge_cbt_frenzy', type: 'Combate', name: 'Frenesi', requirements: 'Experiente, Lutar d8+', description: 'Pode jogar um "Dado de Lutar" extra no seu ataque de perto. Paga-se pelo ataque com as mesmas MultiAções.' },
        { id: 'edge_cbt_imp_frenzy', type: 'Combate', name: 'Frenesi Aprimorado', requirements: 'Veterano, Frenesi', description: 'O Personagem pode rolar até 2 "Dados de Lutar" extras dentro da Ação. Rola 3Lutar +1Selvagem.' },
        { id: 'edge_cbt_twoweapons', type: 'Combate', name: 'Lutar com Duas Armas', requirements: 'Novato, Agilidade d8+', description: 'Um Ataque adicional por rodada com segunda arma na mão inábil sem penalidade extra de Múltipla Ação.' },
        
        // --- LIDERANÇA ---
        { id: 'edge_ldr_command', type: 'Liderança', name: 'Comandar', requirements: 'Novato, Astúcia d6+', description: 'Grito de guerra! Todo aliado Comando (no Alcance) ganha +1 para recuperar condição Abalado.' },
        { id: 'edge_ldr_holdline', type: 'Liderança', name: 'Segure a Linha', requirements: 'Experiente, Astúcia d8+, Comandar', description: 'Aliados Comandados ganham +1 em sua Resistência passiva (+1 Toughness) inspirados por você.' },
        { id: 'edge_ldr_inspire', type: 'Liderança', name: 'Inspirar', requirements: 'Experiente, Comandar', description: 'Aliados no Raio rolam sempre testes de recuperar e medo com bônus extra de Espírito (+2).' },
        { id: 'edge_ldr_naturalldr', type: 'Liderança', name: 'Líder Nato', requirements: 'Veterano, Espírito d8+, Comandar', description: 'A Vantagem Comandar passa a permitir o COMPARTILHAMENTO dos SEUS BENES para rolar os aliados PNJ/Extras!.' },
        
        // --- PODER ---
        { id: 'edge_pwr_newpow', type: 'Poder', name: 'Novo Poder', requirements: 'Novato, Ant. Arcano', description: 'Aprende 2 novos poderes de seu Antecedente Arcano.', effects: { pp_mod: 0, power_count: 2 } },
        { id: 'edge_pwr_pp', type: 'Poder', name: 'Pontos de Poder', requirements: 'Novato, Ant. Arcano', description: 'Seu número máximo de PP (Pontos de Poder) aumenta em +5.', effects: { pp_mod: 5 } },
        { id: 'edge_pwr_rapidrech', type: 'Poder', name: 'Recarga Rápida', requirements: 'Experiente, Ant.Arcano', description: 'Seus PP são renovados numa taxa de +1/hora, num total de 1 por hora.', effects: { pp_regen: 1 } },
        { id: 'edge_pwr_imprech', type: 'Poder', name: 'Recarga Aprimorada', requirements: 'Veterano, Recarga Ráp.', description: 'Recupera na fantástica taxa de 2 PPs a cada hora.', effects: { pp_regen: 2 } },
        { id: 'edge_pwr_soul', type: 'Poder', name: 'Dreno de Alma', requirements: 'Experiente, Ant.Arcano', description: 'Use poderes tirando PP da sua própria Alma do Vigor (-1 de Fadiga natural por cada Dreno de PP extra).' },
        { id: 'edge_pwr_channel', type: 'Poder', name: 'Canalizar', requirements: 'Experiente, Ant.Arcano', description: 'Reduz o consumo de um Poder em 1 PP num teste realizado com Ampliação.' },
        
        // --- PROFISSIONAIS ---
        { id: 'edge_prf_ace', type: 'Profissional', name: 'Ás (Piloto)', requirements: 'Novato, Agilidade d8+', description: 'Repara -2 penalidade ao Piloto. Pode gastar 1 Bene (e sofre Absorção) para consertar o veículo de avistar Dano mortal.' },
        { id: 'edge_prf_investigator', type: 'Profissional', name: 'Investigador', requirements: 'Novato, Astúcia d8+, Perceber d8+', description: '+2 em Pesquisar dados físicos e +2 Percepções ocultas.' },
        { id: 'edge_prf_mcgyver', type: 'Profissional', name: 'MacGyver', requirements: 'Novato, Consertar d6+, Ast d6+', description: 'Pode gambiarras temporárias ignorando falta de peças (ignorando -2 a -4 penalidade).' },
        { id: 'edge_prf_medic', type: 'Profissional', name: 'Médico Batalha', requirements: 'Novato, Curar d8+', description: '+1 a testes de Cura se não há Kit de Primeiros Socorros por perto + ignorar distracao.' },
        { id: 'edge_prf_scholar', type: 'Profissional', name: 'Erudito / Cientista', requirements: 'Novato, Ast d8+, Perícia Acadêmica d8+', description: 'O Herói estuda duramente. +2 em UMA perícia com vínculo intelectual ou +1 em 2 à escolha local.' },
        { id: 'edge_prf_thief', type: 'Profissional', name: 'Ladrão', requirements: 'Novato, Agi d8+, Furt d6+', description: '+1 para Atletismo[Escalar]; Furtividade local e Arrombar portas com Crime.' },
        { id: 'edge_prf_woodsman', type: 'Profissional', name: 'Mateiro', requirements: 'Novato, Sobrev d8+', description: '+2 nas rolagens de Sobrevivência e Rastreador na Reta Selvagem.' },
        
        // --- SOCIAIS ---
        { id: 'edge_soc_charis', type: 'Social', name: 'Carismático', requirements: 'Novato, Espírito d8+', description: 'Ganha um Re-rolagem Grátis eterna quando o lance de Persuadir envolver NPCs ou charme pessoal.' },
        { id: 'edge_soc_connections', type: 'Social', name: 'Contatos', requirements: 'Novato', description: 'Um amigo de favor valioso dentro da Polícia, Jornalismo ou submundo. Liga a cada sessão pra ele.' },
        { id: 'edge_soc_retort', type: 'Social', name: 'Retórica / Replica', requirements: 'Novato, Provocar d6+', description: 'Se um agressor tenta Intimidar/Provocar e falhar perante sua Resistência, ROLAGEM Abalado nele.' },
        { id: 'edge_soc_strongwill', type: 'Social', name: 'Vontade Forte', requirements: 'Novato, Ast d6+, Esp d8+', description: '+2 Resistência Passiva/Ativa vs os efeitos da perícia Provocar e do Feitiço Intimidar.' },
        
        // --- ESTRANHAS ---
        { id: 'edge_wrd_beastmaster', type: 'Estranhas', name: 'Mestre das Feras', requirements: 'Novato, Espírito d8+', description: 'Animais se tornam passivos e empáticos ao seu redor. Possui um Animal de Estimação de bônus aliado!' },
        { id: 'edge_wrd_champion', type: 'Estranhas', name: 'Campeão da Luz', requirements: 'Novato, Esp d8+', description: 'Herói Sacro. Dano +2 contra seres corrompidos (Vampiros/Zumbis) e Resistencia +2 contra poderes das Trevas.' },
        { id: 'edge_wrd_danger', type: 'Estranhas', name: 'Senso de Perigo', requirements: 'Novato', description: 'Rolagem de Perceber vs Surpreendido SEM penalidades. Desperta se esfaqueado dormindo.' },
        { id: 'edge_wrd_healer', type: 'Estranhas', name: 'Curandeiro Inato', requirements: 'Novato, Esp d8+', description: 'Imuniza a regra da Golden Hour pra testar CURA numa pessoa.' },
        
        // --- LENDÁRIAS ---
        { id: 'edge_leg_follower', type: 'Lendárias', name: 'Seguidores', requirements: 'Lendário', description: 'Um pelotão ou secto jurou bandeira. Ganha 5 capangas novatos como Companheiros de NPC permanentes.' },
        { id: 'edge_leg_toughbone', type: 'Lendárias', name: 'Duro de Matar', requirements: 'Lendário, Valente', description: 'Reduza -1 à tabela de Ferimentos Críticos caso derrote a Morte.' },
        { id: 'edge_leg_pro', type: 'Lendárias', name: 'O Profissional', requirements: 'Lendário, d12 na Perícia', description: 'As ações da Perícia D12 ignoram 2 pontos de Malus.' },
        { id: 'edge_leg_weapon_mst', type: 'Lendárias', name: 'Mestre das Armas', requirements: 'Lendário, Aparar 8', description: '+1 MÚLTIPLO no Defesa de Aparar final. E +Aumento do Dano contra Surpresos e Flanqueados.', effects: { parry: 1 } },
    ],
    // NOVA ESTRUTURACÃO DE EQUIPAMENTO JSON
    equipment: [
        /* -------- ARMAS BRANCAS (MEDIEVAIS) -------- */
        { id: 'eq_m_dagger', category: 'Armas Brancas', name: 'Adaga/Faca', cost: 25, armor: 0, damage: 'For+d4', minStr: 4, requiresAmmo: false, extraBenefits: 'Peso: 0.5' },
        { id: 'eq_m_halberd', category: 'Armas Brancas', name: 'Alabarda', cost: 250, armor: 0, damage: 'For+d8', minStr: 8, requiresAmmo: false, extraBenefits: 'Alcance 1, Duas mãos. Peso: 3' },
        { id: 'eq_m_staff', category: 'Armas Brancas', name: 'Bastão', cost: 10, armor: 0, damage: 'For+d4', minStr: 4, requiresAmmo: false, extraBenefits: 'Aparar +1, Alcance 1, Duas Mãos. Peso: 2' },
        { id: 'eq_m_club_light', category: 'Armas Brancas', name: 'Clava Leve', cost: 25, armor: 0, damage: 'For+d4', minStr: 4, requiresAmmo: false, extraBenefits: 'Uma marca de brutalidade. Peso: 1' },
        { id: 'eq_m_club_heavy', category: 'Armas Brancas', name: 'Clava Pesada', cost: 50, armor: 0, damage: 'For+d6', minStr: 6, requiresAmmo: false, extraBenefits: 'Uma marca de brutalidade. Peso: 2.5' },
        { id: 'eq_m_sword_short', category: 'Armas Brancas', name: 'Espada Curta', cost: 100, armor: 0, damage: 'For+d6', minStr: 6, requiresAmmo: false, extraBenefits: 'Sabres de cavalaria. Peso: 1' },
        { id: 'eq_m_sword_great', category: 'Armas Brancas', name: 'Espada Grande', cost: 400, armor: 0, damage: 'For+d10', minStr: 10, requiresAmmo: false, extraBenefits: 'Duas mãos. Peso: 3' },
        { id: 'eq_m_sword_long', category: 'Armas Brancas', name: 'Espada Longa', cost: 300, armor: 0, damage: 'For+d8', minStr: 8, requiresAmmo: false, extraBenefits: 'Espadas básicas e cimitarras. Peso: 1.5' },
        { id: 'eq_m_katana', category: 'Armas Brancas', name: 'Katana', cost: 1000, armor: 0, damage: 'For+d6+1', minStr: 6, requiresAmmo: false, extraBenefits: 'Duas mãos. Peso: 1.5' },
        { id: 'eq_m_spear', category: 'Armas Brancas', name: 'Lança', cost: 100, armor: 0, damage: 'For+d6', minStr: 6, requiresAmmo: false, extraBenefits: 'Alcance 1. Aparar +1 se usada 2 mãos. Peso: 1.5' },
        { id: 'eq_m_lance', category: 'Armas Brancas', name: 'Lança de Cavalaria', cost: 300, armor: 0, damage: 'For+d8', minStr: 8, requiresAmmo: false, extraBenefits: 'PA 2 em investidas. Alcance 2, montado apenas. Peso: 3' },
        { id: 'eq_m_mace', category: 'Armas Brancas', name: 'Maça', cost: 100, armor: 0, damage: 'For+d6', minStr: 6, requiresAmmo: false, extraBenefits: 'Peso: 2' },
        { id: 'eq_m_battleaxe', category: 'Armas Brancas', name: 'Machado de Batalha', cost: 300, armor: 0, damage: 'For+d8', minStr: 8, requiresAmmo: false, extraBenefits: 'Peso: 2' },
        { id: 'eq_m_handaxe', category: 'Armas Brancas', name: 'Machado de Mão', cost: 100, armor: 0, damage: 'For+d6', minStr: 6, requiresAmmo: false, extraBenefits: 'Peso: 1' },
        { id: 'eq_m_greataxe', category: 'Armas Brancas', name: 'Machado Grande', cost: 400, armor: 0, damage: 'For+d10', minStr: 10, requiresAmmo: false, extraBenefits: 'PA 2, Aparar -1, Duas mãos. Peso: 3.5' },
        { id: 'eq_m_maul', category: 'Armas Brancas', name: 'Malho', cost: 400, armor: 0, damage: 'For+d10', minStr: 10, requiresAmmo: false, extraBenefits: 'Duas mãos, +2 dano para quebrar objetos. Peso: 5' },
        { id: 'eq_m_flail', category: 'Armas Brancas', name: 'Mangual', cost: 200, armor: 0, damage: 'For+d6', minStr: 6, requiresAmmo: false, extraBenefits: 'Ignora o bônus por escudo. Peso: 1.5' },
        { id: 'eq_m_warhammer', category: 'Armas Brancas', name: 'Martelo de Guerra', cost: 250, armor: 0, damage: 'For+d6', minStr: 6, requiresAmmo: false, extraBenefits: 'Espinhos, PA 1. Peso: 1' },
        { id: 'eq_m_pike', category: 'Armas Brancas', name: 'Pique', cost: 400, armor: 0, damage: 'For+d8', minStr: 8, requiresAmmo: false, extraBenefits: 'Alcance 2, Duas mãos. Peso: 9' },
        { id: 'eq_m_rapier', category: 'Armas Brancas', name: 'Rapieira', cost: 150, armor: 0, damage: 'For+d4', minStr: 4, requiresAmmo: false, extraBenefits: 'Aparar +1. Peso: 1' },

        /* -------- ARMAS BRANCAS (MODERNAS E FUTURISTAS) -------- */
        { id: 'eq_mod_bayonet', category: 'Armas Brancas', name: 'Modernas: Baioneta', cost: 25, armor: 0, damage: 'For+d4', minStr: 4, requiresAmmo: false, extraBenefits: 'For+d6, Aparar +1, Alcance 1 c/rifle duas mãos. Peso: 0.5' },
        { id: 'eq_mod_bangstick', category: 'Armas Brancas', name: 'Modernas: Bastão de Disparo', cost: 5, armor: 0, damage: '3d6', minStr: 6, requiresAmmo: false, extraBenefits: 'Gasta 1 cartucho de escopeta por uso. Recargar: 1 ação. Peso: 1' },
        { id: 'eq_mod_pocketknife', category: 'Armas Brancas', name: 'Modernas: Canivete', cost: 10, armor: 0, damage: 'For+d4', minStr: 4, requiresAmmo: false, extraBenefits: '-2 em Perceber se escondido. Peso: 0.25' },
        { id: 'eq_mod_baton', category: 'Armas Brancas', name: 'Modernas: Cassetete/Porrete', cost: 10, armor: 0, damage: 'For+d4', minStr: 4, requiresAmmo: false, extraBenefits: 'Armazenadas por forças da lei. Peso: 0.5' },
        { id: 'eq_mod_survivalknife', category: 'Armas Brancas', name: 'Modernas: Faca de Sobrevivência', cost: 50, armor: 0, damage: 'For+d4', minStr: 4, requiresAmmo: false, extraBenefits: '+1 em rolagens de Sobrevivência (básico). Peso: 0.5' },
        { id: 'eq_mod_chainsaw', category: 'Armas Brancas', name: 'Modernas: Motoserra', cost: 200, armor: 0, damage: '2d6+4', minStr: 6, requiresAmmo: false, extraBenefits: 'Falha Crítica atinge o próprio usuário. Peso: 10' },
        { id: 'eq_mod_brassknuckles', category: 'Armas Brancas', name: 'Modernas: Soqueiras', cost: 20, armor: 0, damage: 'For+d4', minStr: 4, requiresAmmo: false, extraBenefits: 'Não conta como arma para Defensor Desarmado. Peso: 0.5' },
        
        { id: 'eq_sci_lasersword', category: 'Ficção Científica', name: 'Futuristas: Espada Laser', cost: 1000, armor: 0, damage: 'For+d6+8', minStr: 4, requiresAmmo: false, extraBenefits: 'PA 12. Peso: 1' },
        { id: 'eq_sci_molecularsword', category: 'Ficção Científica', name: 'Futuristas: Espada Molecular', cost: 500, armor: 0, damage: 'For+d8+2', minStr: 6, requiresAmmo: false, extraBenefits: 'PA 4. Peso: 1' },
        { id: 'eq_sci_molecularknife', category: 'Ficção Científica', name: 'Futuristas: Faca Molecular', cost: 250, armor: 0, damage: 'For+d4+2', minStr: 4, requiresAmmo: false, extraBenefits: 'PA 2. Não pode ser arremessada. Peso: 0.25' },

        /* -------- ARMAS DE LONGA DISTÂNCIA (MEDIEVAIS & MODERNAS) -------- */
        { id: 'eq_r_dagger', category: 'Armas de Fogo/Longa Distância', name: 'Medievais: Adaga/Faca (Arremesso)', cost: 25, armor: 0, damage: 'For+d4', minStr: 4, requiresAmmo: false, extraBenefits: 'Dist: 3/6/12. PA -. CdT 1. Peso: 0.5' },
        { id: 'eq_r_bow', category: 'Armas de Fogo/Longa Distância', name: 'Medievais: Arco', cost: 250, armor: 0, damage: '2d6', minStr: 6, requiresAmmo: true, extraBenefits: 'Dist: 12/24/48. PA -. CdT 1. Peso: 1.5' },
        { id: 'eq_r_longbow', category: 'Armas de Fogo/Longa Distância', name: 'Medievais: Arco Longo', cost: 300, armor: 0, damage: '2d6', minStr: 8, requiresAmmo: true, extraBenefits: 'Dist: 15/30/60. PA 1. CdT 1. Peso: 1.5' },
        { id: 'eq_r_crossbow_hand', category: 'Armas de Fogo/Longa Distância', name: 'Medievais: Besta (Engatilhada Manuel)', cost: 250, armor: 0, damage: '2d6', minStr: 6, requiresAmmo: true, extraBenefits: 'Dist: 10/20/40. PA 2. CdT 1. Peso: 2.5' },
        { id: 'eq_r_crossbow_heavy', category: 'Armas de Fogo/Longa Distância', name: 'Medievais: Besta Pesada', cost: 400, armor: 0, damage: '2d8', minStr: 6, requiresAmmo: true, extraBenefits: 'Dist: 15/30/60. PA 2. Recarregar 2 (Reque molinete). Peso: 4' },
        { id: 'eq_r_sling', category: 'Armas de Fogo/Longa Distância', name: 'Medievais: Funda', cost: 10, armor: 0, damage: 'For+d4', minStr: 4, requiresAmmo: true, extraBenefits: 'Dist: 4/8/16. Usa Atletismo. CdT 1. Peso: 0.5' },
        { id: 'eq_r_javelin', category: 'Armas de Fogo/Longa Distância', name: 'Medievais: Lança/Dardo (Arremesso)', cost: 100, armor: 0, damage: 'For+d6', minStr: 6, requiresAmmo: false, extraBenefits: 'Dist: 3/6/12. PA -. CdT 1. Peso: 1.5' },
        { id: 'eq_r_throwingaxe', category: 'Armas de Fogo/Longa Distância', name: 'Medievais: Machado de Arremesso', cost: 100, armor: 0, damage: 'For+d6', minStr: 6, requiresAmmo: false, extraBenefits: 'Dist: 3/6/12. PA -. CdT 1. Peso: 1.5' },
        { id: 'eq_r_net', category: 'Armas de Fogo/Longa Distância', name: 'Medievais: Rede (Balanceada)', cost: 50, armor: 0, damage: '-', minStr: 4, requiresAmmo: false, extraBenefits: 'Dist: 3/6/12. Alvo Enredado. Dureza 10, vul. corte. Peso: 4' },
        
        { id: 'eq_r_compoundbow', category: 'Armas de Fogo/Longa Distância', name: 'Moderna: Arco Composto', cost: 200, armor: 0, damage: 'For+d6', minStr: 6, requiresAmmo: true, extraBenefits: 'Dist: 12/24/48. PA 1. CdT 1. Peso: 1.5' },
        { id: 'eq_r_modcrossbow', category: 'Armas de Fogo/Longa Distância', name: 'Moderna: Besta', cost: 300, armor: 0, damage: '2d6', minStr: 6, requiresAmmo: true, extraBenefits: 'Dist: 15/30/60. PA 2. CdT 1. Peso: 3.5' },

        /* -------- ARMAS DE PÓLVORA NEGRA -------- */
        { id: 'eq_bp_flintlock', category: 'Armas de Fogo/Longa Distância', name: 'Pólvora: Pistola Flintlock', cost: 150, armor: 0, damage: '2d6+1', minStr: 4, requiresAmmo: true, extraBenefits: 'Dist: 5/10/20. Recarregar 3. CdT 1. Peso: 1.5' },
        { id: 'eq_bp_blunderbuss', category: 'Armas de Fogo/Longa Distância', name: 'Pólvora: Bacamarte', cost: 300, armor: 0, damage: '1 a 3d6', minStr: 6, requiresAmmo: true, extraBenefits: 'Dist: 10/20/40. Escopeta. Recarregar 3. CdT 1. Peso: 6' },
        { id: 'eq_bp_brownbess', category: 'Armas de Fogo/Longa Distância', name: 'Pólvora: Brown Bess', cost: 300, armor: 0, damage: '2d8', minStr: 6, requiresAmmo: true, extraBenefits: 'Mosquetes similares. Dist: 10/20/40. Recarregar 3. CdT 1. Peso: 7.5' },
        { id: 'eq_bp_kentucky', category: 'Armas de Fogo/Longa Distância', name: 'Pólvora: Rifle Kentucky', cost: 300, armor: 0, damage: '2d8', minStr: 6, requiresAmmo: true, extraBenefits: 'Dist: 15/30/60. PA 2. Mosquete estriado: Recarregar 4. Peso: 4' },
        { id: 'eq_bp_springfield', category: 'Armas de Fogo/Longa Distância', name: 'Pólvora: Springfield Mod. 1861', cost: 250, armor: 0, damage: '2d8', minStr: 6, requiresAmmo: true, extraBenefits: 'Dist: 15/30/60. Mosquete estriado. Recarregar 3. CdT 1. Peso: 5.5' },
        
        /* -------- ANIMAIS E ARREIOS -------- */
        { id: 'eq_horse', category: 'Aventura/Utilitários', name: 'Cavalo', cost: 300, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Montaria' },
        { id: 'eq_warhorse', category: 'Aventura/Utilitários', name: 'Cavalo de Guerra', cost: 750, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Montaria Treinada' },
        { id: 'eq_saddle', category: 'Aventura/Utilitários', name: 'Sela', cost: 10, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 5' },
        { id: 'eq_fancy_saddle', category: 'Aventura/Utilitários', name: 'Sela Elaborada', cost: 50, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 5' },

        /* -------- EQUIPAMENTO DE AVENTURA -------- */
        { id: 'eq_shackles', category: 'Aventura/Utilitários', name: 'Algemas (grilhões)', cost: 15, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 1' },
        { id: 'eq_quiver', category: 'Aventura/Utilitários', name: 'Aljava', cost: 25, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Acomoda 20 flechas. Peso: 1' },
        { id: 'eq_whistle', category: 'Aventura/Utilitários', name: 'Apito', cost: 2, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: '' },
        { id: 'eq_cam_disp', category: 'Aventura/Utilitários', name: 'Câmera (descartável)', cost: 10, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 0.5' },
        { id: 'eq_cam_digi', category: 'Aventura/Utilitários', name: 'Câmera (digital)', cost: 300, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 0.5' },
        { id: 'eq_cam_norm', category: 'Aventura/Utilitários', name: 'Câmera (normal)', cost: 75, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 1' },
        { id: 'eq_canteen', category: 'Aventura/Utilitários', name: 'Cantil (odre)', cost: 5, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 0.5' },
        { id: 'eq_blanket', category: 'Aventura/Utilitários', name: 'Cobertor', cost: 10, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 2' },
        { id: 'eq_rope_hemp', category: 'Aventura/Utilitários', name: 'Corda de cânhamo', cost: 10, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: '20 metros. Peso: 7.5' },
        { id: 'eq_rope_nylon', category: 'Aventura/Utilitários', name: 'Corda de nylon', cost: 10, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: '20 metros. Peso: 1.5' },
        { id: 'eq_flask', category: 'Aventura/Utilitários', name: 'Frasco (cerâmica)', cost: 5, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 0.5' },
        { id: 'eq_grapple', category: 'Aventura/Utilitários', name: 'Gancho de Escalada', cost: 100, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 1' },
        { id: 'eq_lockpicks_util', category: 'Aventura/Utilitários', name: 'Gazuas', cost: 200, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 0.5' },
        { id: 'eq_umbrella', category: 'Aventura/Utilitários', name: 'Guarda-Chuva', cost: 5, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 1' },
        { id: 'eq_lighter', category: 'Aventura/Utilitários', name: 'Isqueiro', cost: 2, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: '' },
        { id: 'eq_tools', category: 'Aventura/Utilitários', name: 'Kit de Ferramentas', cost: 200, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 2.5' },
        { id: 'eq_firstaid', category: 'Aventura/Utilitários', name: 'Kit de Primeiros Socorros', cost: 10, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Três usos. Peso: 0.5' },
        { id: 'eq_medkit', category: 'Aventura/Utilitários', name: 'Kit Médico', cost: 100, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: '+1 em Curar. Cinco usos ($25 recarga). Peso: 2' },
        { id: 'eq_oil_lantern', category: 'Aventura/Utilitários', name: 'Lamparina', cost: 25, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: '4 horas, 4 quadros raio. Peso: 1.5' },
        { id: 'eq_flashlight', category: 'Aventura/Utilitários', name: 'Lanterna', cost: 20, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: '10 quadros feixe. Peso: 1.5' },
        { id: 'eq_hammer', category: 'Aventura/Utilitários', name: 'Martelo', cost: 10, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 0.5' },
        { id: 'eq_backpack2', category: 'Aventura/Utilitários', name: 'Mochila', cost: 50, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 1' },
        { id: 'eq_glasses', category: 'Aventura/Utilitários', name: 'Óculos', cost: 20, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 0.5' },
        { id: 'eq_oil', category: 'Aventura/Utilitários', name: 'Óleo (meio litro)', cost: 2, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 0.5' },
        { id: 'eq_shovel', category: 'Aventura/Utilitários', name: 'Pá', cost: 5, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 2.5' },
        { id: 'eq_crowbar', category: 'Aventura/Utilitários', name: 'Pé de Cabra', cost: 10, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 1' },
        { id: 'eq_flint', category: 'Aventura/Utilitários', name: 'Pederneira e Aço', cost: 3, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 0.5' },
        { id: 'eq_whetstone', category: 'Aventura/Utilitários', name: 'Pedra de Amolar', cost: 5, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 0.5' },
        { id: 'eq_soap', category: 'Aventura/Utilitários', name: 'Sabão', cost: 1, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 0.1' },
        { id: 'eq_sleepingbag', category: 'Aventura/Utilitários', name: 'Saco de dormir', cost: 25, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Cobreter de inverno. Peso: 2' },
        { id: 'eq_torch', category: 'Aventura/Utilitários', name: 'Tocha', cost: 5, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: '1 hora (4 quadros de raio). Peso: 0.5' },
        { id: 'eq_candle', category: 'Aventura/Utilitários', name: 'Vela', cost: 1, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: '1 hora (2 quadros de raio). Peso: 0.5' },

        /* -------- VESTUÁRIO -------- */
        { id: 'eq_winter_boots', category: 'Aventura/Utilitários', name: 'Vestuário: Botas de Inverno', cost: 100, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 0.5' },
        { id: 'eq_hiking_boots', category: 'Aventura/Utilitários', name: 'Vestuário: Botas, Caminhada', cost: 100, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 1' },
        { id: 'eq_winter_gear', category: 'Aventura/Utilitários', name: 'Equipamento de Inverno', cost: 200, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Capa/Jaqueta. Peso: 1.5' },
        { id: 'eq_camo', category: 'Aventura/Utilitários', name: 'Vestuário Camuflado', cost: 20, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 1.5' },
        { id: 'eq_casual', category: 'Aventura/Utilitários', name: 'Vestuário, Casual', cost: 20, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 1' },
        { id: 'eq_formal', category: 'Aventura/Utilitários', name: 'Vestuário, Formal', cost: 200, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 1.5' },

        /* -------- ELETRÔNICOS E ACESSÓRIOS -------- */
        { id: 'eq_desktop', category: 'Ficção Científica', name: 'Desktop', cost: 800, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 10' },
        { id: 'eq_handheld', category: 'Ficção Científica', name: 'De Mão (Computador)', cost: 250, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 0.5' },
        { id: 'eq_gps', category: 'Ficção Científica', name: 'GPS', cost: 250, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 0.5' },
        { id: 'eq_laptop', category: 'Ficção Científica', name: 'Laptop', cost: 1200, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 2.5' },
        { id: 'eq_bipod', category: 'Armas de Fogo/Longa Distância', name: 'Bipé/Tripé', cost: 100, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Requer 1 ação pra posicionar. Nega Recuo e For Mín. Peso: 1' },
        { id: 'eq_scope', category: 'Armas de Fogo/Longa Distância', name: 'Luneta de Rifle', cost: 100, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Cancela 2 pontos adicionais de pen a Mirar. Peso: 1' },
        { id: 'eq_laser_sight', category: 'Armas de Fogo/Longa Distância', name: 'Mira Laser/Red Dot', cost: 150, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: '+1 Atirar Curta / Média. Peso: 0.5' },

        /* -------- COMIDA, DEFESA E VIGILÂNCIA -------- */
        { id: 'eq_fastfood', category: 'Aventura/Utilitários', name: 'Refeição Fast Food', cost: 8, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 0.5' },
        { id: 'eq_goodmeal', category: 'Aventura/Utilitários', name: 'Boa Refeição (Restaurante)', cost: 15, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: '' },
        { id: 'eq_mre', category: 'Aventura/Utilitários', name: 'RPC (Refeição Pronta para Comer)', cost: 10, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 0.5' },
        { id: 'eq_rations', category: 'Aventura/Utilitários', name: 'Rações de Viagem', cost: 10, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: '5 refeições, dura 1 semana. Peso: 2.5' },
        
        { id: 'eq_stun_gun', category: 'Aventura/Utilitários', name: 'Arma Atordoante', cost: 25, armor: 0, damage: 'Atordoar', minStr: 0, requiresAmmo: false, extraBenefits: 'Dist. 1/2/4. 3 tiros/carga (2h regarcar). Vigor -2 ou Atordoa. Peso: 0.25' },
        { id: 'eq_pepperspray', category: 'Aventura/Utilitários', name: 'Spray de Pimenta', cost: 15, armor: 0, damage: 'Atordoar', minStr: 0, requiresAmmo: false, extraBenefits: 'Sem pen. distância; Máximo 2 quadros(4 metros). 5 Tiros. Vigor -2. Peso: 0.25' },
        
        { id: 'eq_cam_button', category: 'Ficção Científica', name: 'Botão Câmera', cost: 50, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: '12 horas de uso contínuo.' },
        { id: 'eq_bug_mic', category: 'Ficção Científica', name: '"Bug" (Micro-Transmissor)', cost: 30, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: '12 horas de uso contínuo.' },
        { id: 'eq_detector', category: 'Ficção Científica', name: 'Detector de Transmissão', cost: 525, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 0.5' },
        { id: 'eq_wiretap', category: 'Ficção Científica', name: 'Escuta Telefônica', cost: 250, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: '' },
        { id: 'eq_cell_intercept', category: 'Ficção Científica', name: 'Interceptador de Celular', cost: 650, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 2.5' },
        { id: 'eq_repair_phone', category: 'Aventura/Utilitários', name: 'Telefone de Reparos', cost: 150, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Rola Consertar para conectar na linha. Peso: 2' },
        { id: 'eq_parabolic_mic', category: 'Ficção Científica', name: 'Microfone Parabólico', cost: 750, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Ouve sussurros até 200m. Peso: 2' },
        { id: 'eq_nvg', category: 'Ficção Científica', name: 'Óculos de Visão Noturna', cost: 500, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Sem penalidade Iluminação na Penumbra/Escuridão. Dobro = "Ativo" total. Peso: 1.5' },

        /* -------- MUNIÇÃO -------- */
        { id: 'eq_ammo_small', category: 'Armas de Fogo/Longa Distância', name: 'Munição (Balas Pequeno / 50)', cost: 10, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'cal .22 a .32. Peso: 0.5kg/50' },
        { id: 'eq_ammo_med', category: 'Armas de Fogo/Longa Distância', name: 'Munição (Balas Média / 50)', cost: 20, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'cal .9mm a .45. Peso: 1kg/50' },
        { id: 'eq_ammo_large', category: 'Armas de Fogo/Longa Distância', name: 'Munição (Balas Grande / 50)', cost: 50, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'cal .50+. Peso: 7.5kg/50' },
        { id: 'eq_ammo_blackpow', category: 'Armas de Fogo/Longa Distância', name: 'Balas (c/ Pólvora / 10)', cost: 1, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 250g/10' },
        { id: 'eq_batt_pistol', category: 'Ficção Científica', name: 'Baterias Laser (Pistola)', cost: 20, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 0.25' },
        { id: 'eq_batt_rifle', category: 'Ficção Científica', name: 'Baterias Laser (Rifle/SMG)', cost: 20, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 0.5' },
        { id: 'eq_batt_gatling', category: 'Ficção Científica', name: 'Baterias Laser (Gatling)', cost: 50, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 4' },
        { id: 'eq_ammo_shotgun', category: 'Armas de Fogo/Longa Distância', name: 'Cartuchos de Escopeta (25)', cost: 15, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 700g/25' },
        { id: 'eq_ammo_slug', category: 'Armas de Fogo/Longa Distância', name: 'Balas Sólidas (Escopeta 25)', cost: 20, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 700g/25' },
        { id: 'eq_arrows_b', category: 'Armas de Fogo/Longa Distância', name: 'Flechas/Virotes (5)', cost: 1, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 0.5kg/5' },
        { id: 'eq_slingstones_b', category: 'Armas de Fogo/Longa Distância', name: 'Pedras de Funda (20)', cost: 2, armor: 0, damage: '-', minStr: 0, requiresAmmo: false, extraBenefits: 'Peso: 0.5kg/20' },

        /* -------- ARMADURAS ANTIGAS E MEDIEVAIS -------- */
        { id: 'eq_l_jacket', category: 'Armaduras', name: 'Tecido/Couro Leve: Jaqueta', cost: 20, armor: 1, damage: '-', minStr: 4, requiresAmmo: false, extraBenefits: 'Tronco, braços. Peso: 2.5' },
        { id: 'eq_l_cloak', category: 'Armaduras', name: 'Tecido/Couro Leve: Manto', cost: 30, armor: 1, damage: '-', minStr: 4, requiresAmmo: false, extraBenefits: 'Tronco, braços, pernas. Peso: 4' },
        { id: 'eq_l_pants', category: 'Armaduras', name: 'Tecido/Couro Leve: Calças', cost: 20, armor: 1, damage: '-', minStr: 4, requiresAmmo: false, extraBenefits: 'Pernas. Peso: 2.5' },
        { id: 'eq_l_hood', category: 'Armaduras', name: 'Tecido/Couro Leve: Capuz', cost: 5, armor: 1, damage: '-', minStr: 4, requiresAmmo: false, extraBenefits: 'Cabeça. Peso: 0.5' },
        { id: 'eq_h_jacket', category: 'Armaduras', name: 'Couro Grosso/Pele: Jaqueta', cost: 80, armor: 2, damage: '-', minStr: 6, requiresAmmo: false, extraBenefits: 'Tronco, braços. Peso: 4' },
        { id: 'eq_h_pants', category: 'Armaduras', name: 'Couro Grosso/Pele: Calças', cost: 40, armor: 2, damage: '-', minStr: 6, requiresAmmo: false, extraBenefits: 'Pernas. Peso: 3.5' },
        { id: 'eq_h_hood', category: 'Armaduras', name: 'Couro Grosso/Pele: Capuz', cost: 20, armor: 2, damage: '-', minStr: 6, requiresAmmo: false, extraBenefits: 'Cabeça. Peso: 0.5' },
        
        { id: 'eq_c_shirt', category: 'Armaduras', name: 'Cota de Malha: Camisa', cost: 300, armor: 3, damage: '-', minStr: 8, requiresAmmo: false, extraBenefits: 'Tronco, braços. Peso: 12.5' },
        { id: 'eq_c_pants', category: 'Armaduras', name: 'Cota de Malha: Calças', cost: 150, armor: 3, damage: '-', minStr: 8, requiresAmmo: false, extraBenefits: 'Pernas. Peso: 5' },
        { id: 'eq_c_hood', category: 'Armaduras', name: 'Cota de Malha: Capuz/Elmo', cost: 25, armor: 3, damage: '-', minStr: 8, requiresAmmo: false, extraBenefits: 'Cabeça. Peso: 2' },

        { id: 'eq_b_horse', category: 'Armaduras', name: 'De Bronze: Barda (Cavalo)', cost: 1500, armor: 3, damage: '-', minStr: 10, requiresAmmo: false, extraBenefits: 'Peso: 25' },
        { id: 'eq_b_chest', category: 'Armaduras', name: 'De Bronze: Corselete', cost: 80, armor: 3, damage: '-', minStr: 8, requiresAmmo: false, extraBenefits: 'Tronco. Peso: 6.5' },
        { id: 'eq_b_arms', category: 'Armaduras', name: 'De Bronze: Braçadeiras', cost: 40, armor: 3, damage: '-', minStr: 8, requiresAmmo: false, extraBenefits: 'Braços. Peso: 2.5' },
        { id: 'eq_b_legs', category: 'Armaduras', name: 'De Bronze: Grevas', cost: 50, armor: 3, damage: '-', minStr: 8, requiresAmmo: false, extraBenefits: 'Pernas. Peso: 3' },
        { id: 'eq_b_helm', category: 'Armaduras', name: 'De Bronze: Elmo', cost: 25, armor: 3, damage: '-', minStr: 8, requiresAmmo: false, extraBenefits: 'Cabeça. Peso: 3' },

        { id: 'eq_p_horse', category: 'Armaduras', name: 'Malha de Placas: Barda', cost: 1500, armor: 4, damage: '-', minStr: 10, requiresAmmo: false, extraBenefits: 'Peso: 25' },
        { id: 'eq_p_chest', category: 'Armaduras', name: 'Malha de Placas: Corselete', cost: 500, armor: 4, damage: '-', minStr: 10, requiresAmmo: false, extraBenefits: 'Tronco. Peso: 15' },
        { id: 'eq_p_arms', category: 'Armaduras', name: 'Malha de Placas: Braçadeiras', cost: 200, armor: 4, damage: '-', minStr: 10, requiresAmmo: false, extraBenefits: 'Braços. Peso: 5' },
        { id: 'eq_p_legs', category: 'Armaduras', name: 'Malha de Placas: Grevas', cost: 200, armor: 4, damage: '-', minStr: 10, requiresAmmo: false, extraBenefits: 'Pernas. Peso: 5' },
        { id: 'eq_p_helm', category: 'Armaduras', name: 'Malha de Placas: Elmo Pesado', cost: 100, armor: 4, damage: '-', minStr: 10, requiresAmmo: false, extraBenefits: 'Cabeça. Peso: 2' },
        { id: 'eq_p_helm_closed', category: 'Armaduras', name: 'Placas: Elmo Pesado, Fechado', cost: 200, armor: 4, damage: '-', minStr: 10, requiresAmmo: false, extraBenefits: 'Cabeça. -1 Perceber visão. Peso: 4' },

        /* -------- ARMADURAS MODERNAS -------- */
        { id: 'eq_m_coat', category: 'Armaduras', name: 'Couro: Casaco Grosso', cost: 100, armor: 1, damage: '-', minStr: 4, requiresAmmo: false, extraBenefits: 'Tronco, braços. Peso: 2.5' },
        { id: 'eq_m_pants', category: 'Armaduras', name: 'Couro: Calções para Cavalgar', cost: 70, armor: 1, damage: '-', minStr: 4, requiresAmmo: false, extraBenefits: 'Pernas. Peso: 2.5' },
        { id: 'eq_mk_jacket', category: 'Armaduras', name: 'Kevlar: Jaqueta Moto', cost: 350, armor: 2, damage: '-', minStr: 4, requiresAmmo: false, extraBenefits: 'Tronco, braços. Peso: 4' },
        { id: 'eq_mk_pants', category: 'Armaduras', name: 'Kevlar: Calças Moto', cost: 175, armor: 2, damage: '-', minStr: 4, requiresAmmo: false, extraBenefits: 'Pernas. Peso: 2' },
        { id: 'eq_bike_helm', category: 'Armaduras', name: 'Capacete de Bicicleta', cost: 50, armor: 2, damage: '-', minStr: 4, requiresAmmo: false, extraBenefits: 'Cabeça. Peso: 0.5' },
        { id: 'eq_moto_helm', category: 'Armaduras', name: 'Capacete de Motociclista', cost: 100, armor: 3, damage: '-', minStr: 4, requiresAmmo: false, extraBenefits: 'Cabeça. Peso: 1.5' },

        { id: 'eq_flak', category: 'Armaduras', name: 'Jaqueta Prova Balas (Vietnã)', cost: 40, armor: 2, damage: '-', minStr: 6, requiresAmmo: false, extraBenefits: 'Tronco. Peso: 5' },
        { id: 'eq_kev', category: 'Armaduras', name: 'Colete de Kevlar', cost: 200, armor: 2, damage: '-', minStr: 6, requiresAmmo: false, extraBenefits: 'Tronco. (*) reduz dano em 4 vs balas. Peso: 2.5' },
        { id: 'eq_kev_plates', category: 'Armaduras', name: 'Colete Kevlar com placas', cost: 500, armor: 4, damage: '-', minStr: 8, requiresAmmo: false, extraBenefits: 'Tronco. (*) reduz dano em 4 vs balas. Peso: 8.5' },
        { id: 'eq_kev_helm', category: 'Armaduras', name: 'Capacete de Kevlar', cost: 80, armor: 4, damage: '-', minStr: 4, requiresAmmo: false, extraBenefits: 'Cabeça. (*) reduz dano em 4 vs balas. Peso: 2.5' },
        { id: 'eq_bomb_s', category: 'Armaduras', name: 'Traje Antibombas', cost: 25000, armor: 10, damage: '-', minStr: 12, requiresAmmo: false, extraBenefits: 'Corpo Intel. Agilidade máx d6, Mov -2. Peso: 40' },

        /* -------- ARMADURAS FUTURÍSTICAS -------- */
        { id: 'eq_laser_s', category: 'Armaduras', name: 'Armadura Corporal (Leve)', cost: 200, armor: 4, damage: '-', minStr: 4, requiresAmmo: false, extraBenefits: 'Tronco, br., pernas. (*). Adicionar "Pele Energética"=+50% $. Peso: 2' },
        { id: 'eq_infantry', category: 'Armaduras', name: 'Traje Batalha Infantaria', cost: 800, armor: 6, damage: '-', minStr: 6, requiresAmmo: false, extraBenefits: 'Tronco, br., pernas. (*). Botas e Luvas. Peso: 6' },
        { id: 'eq_infantry_h', category: 'Armaduras', name: 'Capacete de Batalha', cost: 100, armor: 6, damage: '-', minStr: 6, requiresAmmo: false, extraBenefits: 'Cabeça/Rosto. (*). Peso: 1' },

        /* -------- ESCUDOS -------- */
        { id: 'eq_shd_small', category: 'Escudos', name: 'Antigas/Medievais: Pequeno', cost: 50, armor: 0, damage: 'For+d4', minStr: 4, requiresAmmo: false, extraBenefits: 'Aparar +1. Cobertura -. Dureza 10 (+2 Armadura tiro através). Peso: 2' },
        { id: 'eq_shd_med', category: 'Escudos', name: 'Antigas/Medievais: Média', cost: 100, armor: 0, damage: 'For+d4', minStr: 6, requiresAmmo: false, extraBenefits: 'Aparar +2. Cobertura -2. Dureza 10 (+2 Arm). Peso: 4' },
        { id: 'eq_shd_large', category: 'Escudos', name: 'Antigas/Medievais: Grande', cost: 200, armor: 0, damage: 'For+d4', minStr: 8, requiresAmmo: false, extraBenefits: 'Aparar +3. Cobertura -4. Dureza 10 (+2 Arm). Peso: 6' },
        
        { id: 'eq_shd_riot', category: 'Escudos', name: 'Modernas: Escudo Anti choque', cost: 80, armor: 0, damage: 'For+d4', minStr: 4, requiresAmmo: false, extraBenefits: 'Aparar +3. Cobertura -4. Dureza 12 (+2 Arm). Peso: 2.5' },
        { id: 'eq_shd_ballistic', category: 'Escudos', name: 'Modernas: Escudo Balístico', cost: 250, armor: 0, damage: 'For+d4', minStr: 6, requiresAmmo: false, extraBenefits: 'Aparar +3. Cobertura -4. Reduz dano fogo em 4. Peso: 4.5' },

        { id: 'eq_pol_small', category: 'Escudos', name: 'Futuristas: Polímero, Pequeno', cost: 200, armor: 0, damage: 'For+d4', minStr: 4, requiresAmmo: false, extraBenefits: 'Aparar +1. Cobertura -. Dureza 10 (+4 Arm). Peso: 1' },
        { id: 'eq_pol_med', category: 'Escudos', name: 'Futuristas: Polímero, Médio', cost: 300, armor: 0, damage: 'For+d4', minStr: 4, requiresAmmo: false, extraBenefits: 'Aparar +2, Cobertura -2. Dureza 10 (+4 Arm). Peso: 2' },
        { id: 'eq_pol_large', category: 'Escudos', name: 'Futuristas: Polímero, Grande', cost: 400, armor: 0, damage: 'For+d4', minStr: 6, requiresAmmo: false, extraBenefits: 'Aparar +3, Cobertura -4. Dureza 10 (+4 Arm). Peso: 3' }
    ],
    powers: [
        { id: 'pow_adivinhacao', name: 'Adivinhação', rank: 'Heroico', pp: 5, range: 'Pessoal', duration: '5 min.', description: 'Faz contato com outro plano para fazer uma pergunta por rodada. Modificadores: Nenhum.' },
        { id: 'pow_ajuda', name: 'Ajuda', rank: 'Novato', pp: 1, range: 'Astúcia', duration: 'Instantâneo', description: 'Remove 1 Fadiga ou o estado Abalado (com Ampliação remove Atordoado). Modificadores: Receptores Adicionais (+1).' },
        { id: 'pow_amigo_feras', name: 'Amigo das Feras', rank: 'Novato', pp: 'Especial', range: 'Astúcia', duration: '10 min.', description: 'Controla um animal (PP = Tamanho, máx 0, mín 1). Modificadores: Receptores Adicionais (+1), Controle Mental (+2).' },
        { id: 'pow_andar_paredes', name: 'Andar nas Paredes', rank: 'Novato', pp: 2, range: 'Astúcia', duration: '5', description: 'Move-se em superfícies verticais com metade do deslocamento (normal com Ampliação). Modificadores: Receptores Adicionais (+1).' },
        { id: 'pow_atordoar', name: 'Atordoar', rank: 'Novato', pp: 2, range: 'Astúcia', duration: 'Instantâneo', description: 'Causa estado Atordoado numa rolagem resistida contra Vigor. Modificadores: Área (+2/+3).' },
        { id: 'pow_aumentar_reduzir_atributo', name: 'Aumentar/Reduzir Característica', rank: 'Novato', pp: 2, range: 'Astúcia', duration: '5 / Inst.', description: 'Aumenta perícia/atributo do aliado por 5 turnos ou abaixa permanentemente de um oponente até que ele resista. Modificadores: Receptores Adicionais (+1), Forte (+1).' },
        { id: 'pow_banir', name: 'Banir', rank: 'Veterano', pp: 3, range: 'Astúcia', duration: 'Instantâneo', description: 'Expulsa entidades invocadas. Rolagem resistida (sucesso = Abalado, ampliação = 1 Feri). Se o alvo Inacapacitar, é banido. Modificadores: Nenhum.' },
        { id: 'pow_barreira', name: 'Barreira', rank: 'Experiente', pp: 2, range: 'Astúcia', duration: '5', description: 'Cria uma parede durável de espessura 10 (12 com Ampliação), bloqueando ataques. Modificadores: Dano 2d4 (+1), Endurecida (+1), Modelado (+2), Tamanho (+1).' },
        { id: 'pow_campo_de_dano', name: 'Campo de Dano', rank: 'Experiente', pp: 4, range: 'Astúcia', duration: '5', description: 'Cria aura flamejante em torno de você em que qualquer alvo adjacente sofre 2d4 de dano automático todo fim de turno. Modificadores: Área Explosão (+2/+3), Dano Maior (+2), Dano Focado (+1/2 PP), Duração Aumentada (+1/+2).' },
        { id: 'pow_cavar', name: 'Cavar', rank: 'Novato', pp: 2, range: 'Astúcia', duration: '5', description: 'Derrete pela terra na metade do deslocamento para fugir de ataques ou atacar furtivamente. Modificadores: Receptores Adicionais (+1), Poder/Pedra (+1).' },
        { id: 'pow_cegar', name: 'Cegar', rank: 'Novato', pp: 2, range: 'Astúcia', duration: 'Instantâneo', description: 'Ilumina fortemente a visão do alvo. Penalidade -2 em visão (-4 com Ampliação). Recupera pelo Vigor. Modificadores: Área (+2/+3), Forte (+1).' },
        { id: 'pow_confusao', name: 'Confusão', rank: 'Novato', pp: 1, range: 'Astúcia', duration: '1 Turno', description: 'Ilusões confusas deixam o alvo Distraído e Vulnerável (recupera fim do próx turno). Modificadores: Área (+2/+3).' },
        { id: 'pow_conjurar_aliado', name: 'Conjurar Aliado', rank: 'Novato', pp: '2+', range: 'Astúcia', duration: '5', description: 'Molda constructo subordinado que atua no seu turno (Custo e poder baseados no Rank, como Guarda Costas 4, Sentinela 8). Modificadores: Nenhum (escalona por Rank).' },
        { id: 'pow_crescimento_encolhimento', name: 'Crescimento / Encolhimento', rank: 'Experiente', pp: '2/pt', range: 'Astúcia', duration: '5', description: 'Altera fisiologia e tamanho (-/+ atributos físicos a cada ponto de tamanho alterado). Modificadores: Nenhum.' },
        { id: 'pow_cura', name: 'Cura', rank: 'Novato', pp: 3, range: 'Toque', duration: 'Instantâneo', description: 'Cura até 2 Ferimentos sofridos na última hora. Falhas críticas ferem a pessoa ou a você. Modificadores: Cura Maior (>1h +10), Lesão Debilitante (+20), Neutralizar Veneno (+1).' },
        { id: 'pow_dadiva_do_guerreiro', name: 'Dádiva do Guerreiro', rank: 'Experiente', pp: 4, range: 'Astúcia', duration: '5', description: 'Concede temporariamente os benefícios de uma única Vantagem de Combate que você possua o nível equivalente ao alvo. Modificadores: Receptores Adicionais (+1).' },
        { id: 'pow_deflexao', name: 'Deflexão', rank: 'Novato', pp: 3, range: 'Astúcia', duration: '5', description: 'Distorce os vetores contra você. Inimigos atacam seu grupo com penalidade passiva de -2 ou -4. Modificadores: Receptores Adicionais (+1).' },
        { id: 'pow_detectar_ocultar_arcano', name: 'Detectar / Ocultar Arcano', rank: 'Novato', pp: 2, range: 'Astúcia', duration: '5 / 1h', description: 'Permite enxergar presenças mágicas ignorando Invs (-4). Ocultar blinda assinaturas arcanas passivamente por 1h. Modificadores: Receptores Adicionais (+1), Área (+1/+2), Forte (+1).' },
        { id: 'pow_devastacao', name: 'Devastação', rank: 'Novato', pp: 2, range: 'Astúcia', duration: 'Instantâneo', description: 'Onda letal em Exp. Média ou Cone; alvos sofrem Força (menos se em voo). São Distraídos ou Arremessados 2d6. Possível Dano Secundário. Modificadores: Área (+1), Forte (+1).' },
        { id: 'pow_disfarce', name: 'Disfarce', rank: 'Experiente', pp: 2, range: 'Astúcia', duration: '10 min', description: 'Simula um alter-ego cosmético sob Perceber -2 em suspeitos (-4 com Ampliação). Modificadores: Receptores Adicionais (+1), Tamanho (+1).' },
        { id: 'pow_dissipar', name: 'Dissipar', rank: 'Experiente', pp: 1, range: 'Astúcia', duration: 'Instantâneo', description: 'Interrompe feitiços em andamento como Interrupção em espera. Rola embate Arcano vs Arcano. Falha nega a magia. Modificadores: Poder Permanente (+1).' },
        { id: 'pow_drenar_pontos_de_poder', name: 'Drenar Pontos de Poder', rank: 'Veterano', pp: 2, range: 'Astúcia', duration: 'Instantâneo', description: 'Extrai 1d6 PP do seu inimigo numa rolagem resistida (-2 se conjuração diferir). Com ampliação absorve para si. Modificadores: Nenhum.' },
        { id: 'pow_elo_mental', name: 'Elo Mental', rank: 'Novato', pp: 1, range: 'Astúcia', duration: '30 min', description: 'Rádio telepático no grupo (alcance de 2 km, 8 km ampliado). Se 1 tomar ferimento todos fazem Teste de Abalado de susto. Modificadores: Receptores Adicionais (+1).' },
        { id: 'pow_empatia', name: 'Empatia', rank: 'Novato', pp: 1, range: 'Astúcia', duration: '5', description: 'Molda os ímpetos emocionais adversários contra eles, recebe +2 (+4) em Testes Sociais contra o Alvo. Modificadores: Nenhum.' },
        { id: 'pow_enredar', name: 'Enredar', rank: 'Novato', pp: 2, range: 'Astúcia', duration: 'Instantâneo', description: 'Alvo Enredado (Força -2, Agilidade vs Arcano) por lianas no chão, com Ampliação fica completamente preso. Modificadores: Área (+2/+3), Material Forte (+2).' },
        { id: 'pow_explosao', name: 'Explosão', rank: 'Experiente', pp: 3, range: 'Astx2', duration: 'Instantâneo', description: 'Lança área letal (E. Media) causando 2d6 (+ampl). Sem custo de mira. Modificadores: Área (+0/+1), Dano 3d6/4d6 (+2).' },
        { id: 'pow_falar_idioma', name: 'Falar Idioma', rank: 'Novato', pp: 1, range: 'Astúcia', duration: '10 min', description: 'Fala fluente um idioma (1 por Cast), com ampliação adota maneirismos socioculturais. Modificadores: Receptores Adicionais (+1).' },
        { id: 'pow_fantoche', name: 'Fantoche', rank: 'Veterano', pp: 3, range: 'Astúcia', duration: '5', description: 'Domina mentes (Arcano vs Espírito do Alvo). Pode usar para ordens básicas (ataque aquele, fuja daquele), não usa perícia complexa. Modificadores: Receptores Adicionais (+2).' },
        { id: 'pow_ferir', name: 'Ferir', rank: 'Novato', pp: 2, range: 'Astúcia', duration: '5', description: 'Impregna uma arma Corpo-a-Corpo ou Pente de arma de Fogo com poder sagrado para rolar Dano Físico Extra de +2 (ou +4 ampl). Modificadores: Receptores Adicionais (+1).' },
        { id: 'pow_iluminar_obscurecer', name: 'Iluminar/Obscurecer', rank: 'Novato', pp: 2, range: 'Astúcia', duration: '10 min', description: 'Gera Luz Intensa ou trevas (M. Grande / Breu 10 quadros). Alvos ali tem -6/+0 Visão. Sobreposições fazem penumbra -2. Modificadores: Móvel (+1), Focado no Alvo (+2).' },
        { id: 'pow_ilusao', name: 'Ilusão', rank: 'Novato', pp: 3, range: 'Astúcia', duration: '5', description: 'Fábrica holográfico (Area Med), sem colisão. Personagens duvidando fazem Ast. Teste livre pra ignorar fantasmas. Modificadores: Som Sinergizado (+1), Convincente (+2).' },
        { id: 'pow_intangibilidade', name: 'Intangibilidade', rank: 'Heroico', pp: 5, range: 'Astúcia', duration: '5', description: 'Virar fumaça ou espectro físico (Não é afetado por armas materiais e pode atravessar paredes mas toma Dano Arcano ou Mágico). Modificadores: Nenhum.' },
        { id: 'pow_invisibilidade', name: 'Invisibilidade', rank: 'Experiente', pp: 5, range: 'Astúcia', duration: '5', description: 'Filtra assinaturas visuais (Mirar/Ataque vs você tem um forte malus de -4/-6). Modificadores: Receptores Adicionais (+3).' },
        { id: 'pow_leitura_objeto', name: 'Leitura de Objeto', rank: 'Experiente', pp: 2, range: 'Toque', duration: 'Especial', description: 'Sente eventos ligados a um artefato por 5 anos passados (Ases: até 100 anos). Modificadores: Emoção Embutida (+2).' },
        { id: 'pow_leitura_mental', name: 'Leitura Mental', rank: 'Novato', pp: 2, range: 'Astúcia', duration: 'Inst.', description: 'Extrai passivamente 1 resposta verdadeira em Mente vs. Mente. Alvo percebe interferência neural. Modificadores: N/a' },
        { id: 'pow_limpeza_mental', name: 'Limpeza Mental', rank: 'Veterano', pp: 3, range: 'Astúcia', duration: 'Inst.', description: 'Força alvo apagar meia hora de evento mental em trauma arcano resistido. Ampliação = Esquece complexos dias inteiros. Modificadores: Editar/Remodelar em Vez de Apagar (+1), Rápido Cast (+2).' },
        { id: 'pow_manipulacao_elemental', name: 'Manipulação Elemental', rank: 'Novato', pp: 1, range: 'Astúcia', duration: '5', description: 'Modulação mágica dos 4 elementos em coisas menores: afastar areias ou levantar fumaças (Dá -2 no inimigo ou d6 Dano baixo na mão). Modificadores: Nenhum.' },
        { id: 'pow_medo', name: 'Medo', rank: 'Novato', pp: 2, range: 'Astúcia', duration: 'Inst.', description: 'Provoca terror (Role tabela do Teste de Medo). Com ampliação alvos tiram -2 em Coragem. Extras fogem apavorados. Modificadores: Área E.M e E.G (+2/+3).' },
        { id: 'pow_morosidade_velocidade', name: 'Morosidade / Velocidade', rank: 'Experiente', pp: 2, range: 'Astúcia', duration: 'Inst / 5', description: 'Velocidade tira custo de corrida e dobra o mov (+ampliação reduz as penalidades de até 3 mult ações). Lerdeza paralisa (-2 mov e ação) o outro em Rolagem resistida de Espirito. Modificadores: Receptor (+1), Área Lerdeza (+2), Velocidade Rapidez (-2 multi ação buffer) (+2).' },
        { id: 'pow_mudanca_de_forma', name: 'Mudança de Forma', rank: 'Novato', pp: 'Esp', range: 'Pessoal', duration: '5', description: 'Mimetiza formas animais conforme Rank de Poder (pág. 199). Ases aumentam num dado de rank o Vigor/Força animal adotada. Modificadores: Voz Ativa (+1).' },
        { id: 'pow_protecao', name: 'Proteção', rank: 'Novato', pp: 1, range: 'Astúcia', duration: '5', description: 'Cria uma armadura mística ao redor do alvo, concedendo +2 Armadura (ou +4 com ampliação). Acumula com trajes convencionais mundanos/futuristas. Modificadores: Receptores (+1), Mais Arm (+1), Converter pra Resistência Absoluta (+2).' },
        { id: 'pow_protecao_ambiental', name: 'Proteção Ambiental', rank: 'Novato', pp: 2, range: 'Astúcia', duration: '1 hora', description: 'Inibe pressões vitais de radiação, Magma, Espaço ou respiração sob água. Subitrai passivamente 4 (ou 6) pontos nos danos de ataques hostis elementais em questão. Modificadores: Receptores (+1).' },
        { id: 'pow_protecao_arcana', name: 'Proteção Arcana', rank: 'Novato', pp: 1, range: 'Astúcia', duration: '5', description: 'O alvo é amparado ganhando passivamente a habilidade mecânica Resistência Arcana base do Livro de Regras (+2 em rolagens contra Magia, e reduz -2 de danos magicos). Modificadores: Receptores (+1).' },
        { id: 'pow_raio', name: 'Raio', rank: 'Novato', pp: 1, range: 'Astx2', duration: 'Inst.', description: 'Arremessa fragmentos base 2d6, explodem em Ases. Multiplique o custo para enviar de 2 até 3 Raios isoladamente nas vítimas simulando Recuo em Ações independentes (Max 3). Modificadores: Dano pesado de 3d6/4d6 (+2).' },
        { id: 'pow_rajada', name: 'Rajada', rank: 'Novato', pp: 2, range: 'Cone', duration: 'Inst', description: 'Projeção Cone passivo emanando do Conjurador de Dano base 2d6. Oponentes no Cone não tem o direito de Esquiva tradicional. Modificadores: Dano Bruto 3d6/4d6 (+2).' },
        { id: 'pow_ressurreicao', name: 'Ressurreição', rank: 'Heroico', pp: 30, range: 'Toque', duration: 'Inst.', description: 'Ressucita mortos recentes (-1 ano, rolagem resistida terrível -8 que gasta 4 horas na conjuração curandeira). Alvo recomeça morto-vivo/Exausto c/ 3 Ferimentos já de cara. Modificadores: Cadáver Histórico Máquina do Tempo de até 10 Anos (+5).' },
        { id: 'pow_som_silencio', name: 'Som / Silêncio', rank: 'Novato', pp: 1, range: 'Astúcia / x5', duration: '5', description: 'Silencia passivamente Modulos Grandes prejudicando -4 de Perceber. Ases ensurdecem 100%. Pode gerar ilusão sônica passiva de Grito em oponentes na nuca dos mesmos. Modificadores: Área Móvel (+1), Focado no Alvo resistido (-2).' },
        { id: 'pow_sono', name: 'Sono', rank: 'Experiente', pp: 2, range: 'Astúcia', duration: '1 Hora', description: 'Sedativo Arcano em Alvos falhos num teste de Vigor os faz dormir pela duração contínua pesadamente. Agitações violentas e barulhos altos os força num re-teste. Modificadores: Área Exp M e G (+2/+3).' },
        { id: 'pow_telecinese', name: 'Telecinese', rank: 'Experiente', pp: 5, range: 'Astx2', duration: '5', description: 'Traciona alvos usando uma força motora d10 (D12). Arrasta alvos ou objetos. Arremessa com violência gerando (Dano For+d6 no arremesso). Permite manuseio Mágico de Ferramentas / Armas flutuantes! Modificadores: Nenhum.' },
        { id: 'pow_teleporte', name: 'Teleporte', rank: 'Experiente', pp: 2, range: 'Astúcia', duration: 'Inst.', description: 'Pula 12 a 24 quadros invisivelmente em um balanço temporal (-2 se através de paredes). Inimigo adjancente atual não ganha ataque de Oportunidades. Voluntários viajam contigo. Modificadores: Receptores (+1), Puxar/Empurrar Inimigo Teletransporte Agressivo (+2).' },
        { id: 'pow_visao_distante', name: 'Visão Distante', rank: 'Experiente', pp: 2, range: 'Astúcia', duration: '5', description: 'Lente binócular telepática garantindo ver até 1.5 quilometro passivamente com detalhes macro, Ases reduzem Range penalties para rolagens Metade. Modificadores: Receptores (+1).' },
        { id: 'pow_visao_sombria', name: 'Visão Sombria', rank: 'Novato', pp: 1, range: 'Astúcia', duration: '1 Hora', description: 'Neutraliza e filtra completamente as penumbras cortando até -4 no malus ou Remove Breu absoluto se passar com ampliação por uma hora em seus receptores. Modificadores: Receptores (+1).' },
        { id: 'pow_voar', name: 'Voar', rank: 'Veterano', pp: 3, range: 'Astúcia', duration: '5', description: 'Compele voo aos céus base 12 Mod Quad. ou x2 ampliada sem precisar de movimentos Sprint contínuos (Pode parear perfeitamente suspensos no ar). Modificadores: Receptores (+2pp caa).' },
        { id: 'pow_zumbi', name: 'Zumbi', rank: 'Veterano', pp: 3, range: 'Astúcia', duration: '1 Hora', description: 'Reanima Cadaver Morto ou Criatura (+3). Baseado do Esqueleto 3 PP; Uma horda pode ser sumonada por 1 extra pp cada limitando rolagens. Conjurador é soberano dos servos. Modificadores: Adicionais (+1/cada), Armadura Enferrujada (+1/zumbi), Arma comum (+1/zumbi), Passageiro da Mente ligamento mental (+1), Cadáveres Permanentes (o PP gasto nisso fica travado irreganhável).' }
    ],
    racialAbilitiesPos: [
        { id: 'rap_action', name: 'Ação Adicional', cost: 3, type: 'checkbox', desc: 'O ser tem apêndices adicionais, reflexos melhorados ou uma coordenação óculo-manual excepcional. Ele pode ignorar 2 pontos de penalidades por Ações Múltiplas a cada turno.' },
        { id: 'rap_adaptable', name: 'Adaptável', cost: 2, type: 'checkbox', desc: 'A raça é bem variada entre seu povo e cultura. Personagens começam com uma Vantagem de nível Novato de sua escolha (e devem preencher todos os requisitos).' },
        { id: 'rap_reach', name: 'Alcance', cost: 1, max: 3, type: 'stack', desc: 'Tentáculos ou outros tipos de membros alongados concedem Alcance +1 à criatura (adicione +1 cada vez que for escolhida depois da primeira).' },
        { id: 'rap_wallwalker', name: 'Andar Pelas Paredes', cost: 1, type: 'checkbox', desc: 'A espécie pode andar em superfícies verticais normalmente, ou em superfícies invertidas com metade do deslocamento.' },
        { id: 'rap_parry', name: 'Aparar', cost: 1, max: 3, type: 'stack', desc: 'O Aparar natural da criatura é aumentado em +1. Isso pode ser devido a uma cauda preênsil, membros extras, reflexos aprimorados ou mesmo um sentido psiônico latente.' },
        { id: 'rap_aquatic', name: 'Aquático/Semi-Aquático', cost: 1, type: 'upgrade', desc: 'Afinidade com ambientes líquidos.', levels: [
            { cost: 1, name: 'Semi-Aquático', desc: 'O personagem é semi-aquático e pode prender a respiração por 15 minutos antes de testes de afogamento.' },
            { cost: 2, name: 'Aquático Pleno', desc: 'Ele é um nativo da água. Ele não pode se afogar em líquido oxigenado e se move com sua Movimentação completa quando nada.' }
        ]},
        { id: 'rap_armor', name: 'Armadura Natural', cost: 1, max: 3, type: 'stack', desc: 'A espécie tem uma pele grossa ou é incrustada por materiais sólidos como placas ou até mesmo rocha. Isso garante Armadura +2 cada vez que é comprada.' },
        { id: 'rap_attr_boost', name: 'Aumento de Atributo', cost: 2, max: 5, type: 'multiItem', requireInput: 'select', options: ['Agilidade', 'Astúcia', 'Espírito', 'Força', 'Vigor'], desc: 'Durante a criação de personagem, a espécie aumenta um atributo específico em um tipo de dado. Isso também aumenta o máximo da Característica em um.' },
        { id: 'rap_skill_bonus', name: 'Bônus de Perícia', cost: 2, max: 5, type: 'multiItem', requireInput: 'text', desc: 'O personagem tem um bônus de +2 quando usa uma perícia específica (isso só pode ser comprado uma vez por perícia).' },
        { id: 'rap_burrow', name: 'Cavar', cost: 1, type: 'checkbox', desc: 'A espécie pode se enterrar e se mover sob a terra comum com a metade de sua Movimentação (não pode correr). Pode surpreender oponentes.' },
        { id: 'rap_horns', name: 'Chifres', cost: 1, type: 'upgrade', desc: 'Ataques desarmados com a cabeça ganham dano massivo.', levels: [
            { cost: 1, name: 'For+d4', desc: 'O ser tem um chifre, ou chifres, que causam For+d4 de dano.' },
            { cost: 2, name: 'For+d6', desc: 'O ser tem um chifre, ou chifres, que causam For+d6 de dano.'}
        ]},
        { id: 'rap_construct', name: 'Construto', cost: 8, type: 'checkbox', desc: 'Construtos são seres artificiais feitos de material inorgânico. Eles adicionam +2 para se recuperar do Estado de Abalado, ignoram um nível de mod de Ferimento, não respiram e são imunes a doenças e venenos.' },
        { id: 'rap_claws', name: 'Garras', cost: 2, type: 'upgrade', desc: 'Membros afiados substitutos a ataques desarmados.', levels: [
            { cost: 2, name: 'For+d4', desc: 'A raça tem garras que causam Força +d4 de dano.' },
            { cost: 3, name: 'For+d6', desc: 'Aumenta seu dano para Força +d6.' },
            { cost: 4, name: 'For+d6 PA 2', desc: 'Adiciona PA 2 as garras.' }
        ]},
        { id: 'rap_immune', name: 'Imune a Doenças e Venenos', cost: 1, type: 'upgrade', desc: 'A espécie é imune a doenças ou venenos.', levels: [
            { cost: 1, name: 'Imunidade Unica', desc: 'Imune Apenas a Viroses ou Toxinas.', requireInput: 'select', options: ['Venenos Toxológicos', 'Doenças Virais/Bacterianas'] },
            { cost: 2, name: 'Imunidade Completa', desc: 'Pode ser comprado duas vezes para ambos os efeitos.' }
        ]},
        { id: 'rap_infravision', name: 'Infravisão', cost: 1, type: 'checkbox', desc: 'A criatura “vê” calor. Diminui à metade penalidades por Iluminação quando se ataca alvos quentes.' },
        { id: 'rap_bite', name: 'Mordida', cost: 1, type: 'checkbox', desc: 'A raça tem presas que causam Força +d4 de dano.' },
        { id: 'rap_pace', name: 'Movimentação', cost: 2, max: 2, type: 'stack', desc: 'A Movimentação do personagem aumenta em +2 e seu dado de corrida aumenta em um tipo.' },
        { id: 'rap_nobreathe', name: 'Não Respira', cost: 2, type: 'checkbox', desc: 'A espécie não respira. Os indivíduos não são afetados por toxinas inaladas, não se afogam e não sufocam no vácuo.' },
        { id: 'rap_skill', name: 'Perícia', cost: 1, max: 5, type: 'multiItem', requireInput: 'text', desc: 'O personagem começa com um d4 em uma perícia inerente a sua raça.', levels: [
            { cost: 1, name: 'Básica Inata', desc: 'Ela começa com d4.' },
            { cost: 2, name: 'Aprimorada Inata', desc: 'Ela começa em d6 e o máximo da perícia aumenta para d12+1.' }
        ]},
        { id: 'rap_power_base', name: 'Poder Arcano (Base)', cost: 2, type: 'multiItem', max: 1, requireInput: 'text', desc: 'A raça tem uma habilidade inata que funciona como um poder. Ela tem o Antecedente Arcano (Dom) e um poder.' },
        { id: 'rap_power_add', name: 'Poder Arcano (Extra)', cost: 1, type: 'multiItem', max: 5, requireInput: 'text', desc: 'Cada vez que é escolhida depois da primeira custa 1 ponto e concede outro poder.' },
        { id: 'rap_sleep', name: 'Redução de Sono', cost: 1, type: 'upgrade', desc: 'Ritmos repousivos reduzidos.', levels: [
            { cost: 1, name: 'Metade do Tempo', desc: 'O ser precisa de metade do tempo de sono normal.' },
            { cost: 2, name: 'Sem Sono', desc: 'Ele nunca dorme.' }
        ]},
        { id: 'rap_regen', name: 'Regeneração', cost: 2, type: 'upgrade', desc: 'O ser cura dano rapidamente.', levels: [
            { cost: 2, name: 'Acelerativa', desc: 'Ele pode fazer uma rolagem de Cura natural uma vez por dia (em vez de uma vez por semana).' },
            { cost: 3, name: 'Permanente', desc: 'Lesões permanentes podem ser recuperadas quando todos os Ferimentos forem regenerados.' }
        ]},
        { id: 'rap_resilience', name: 'Resistência Passiva', cost: 1, max: 3, type: 'stack', desc: 'O personagem possui pele endurecida, escamas ou tecido extremamente denso que aumenta sua Resistência em +1.' },
        { id: 'rap_resisenv', name: 'Resistência Ambiental', cost: 1, max: 5, type: 'multiItem', requireInput: 'text', desc: 'A espécie recebe um bônus de +4 para resistir a um único efeito ambiental negativo como calor, frio, falta de ar. Dano dessa fonte é reduzido em 4.' },
        { id: 'rap_tough', name: 'Robusto', cost: 2, type: 'checkbox', desc: 'Um segundo Resultado Abalado não causa Ferimento.' },
        { id: 'rap_jumper', name: 'Saltador', cost: 2, type: 'checkbox', desc: 'O personagem pode pular o dobro da distância listada. Adiciona +4 ao dano quando salta como parte de um Ataque Selvagem.' },
        { id: 'rap_novitals', name: 'Sem Órgãos Vitais', cost: 1, type: 'checkbox', desc: 'Essas espécies possuem órgãos vitais escondidos. Ataques Localizados não provocam dano extra contra eles.' },
        { id: 'rap_sizeup', name: 'Tamanho +1', cost: 1, max: 3, type: 'stack', desc: 'A criatura é maior do que o normal. Cada ponto de Tamanho soma diretamente na Resistência e aumenta a Força máxima em um nível.' },
        { id: 'rap_venom', name: 'Toque Venenoso', cost: 1, type: 'upgrade', desc: 'Ataque de Toque que envenena quem sofre.', levels: [
            { cost: 1, name: 'Toxidade Leve', desc: 'A vítima deve rolar Vigor ou sofre os efeitos de um Veneno Moderado.' },
            { cost: 3, name: 'Toxidade Grave', desc: 'O veneno pode ser aprimorado para Nocauteador, Letal ou Paralisante.' }
        ]},
        { id: 'rap_edge', name: 'Vantagem', cost: 2, type: 'multiItem', max: 5, requireInput: 'text', desc: 'Todos os membros desta raça têm a mesma Vantagem inata.', levels: [
            { cost: 2, name: 'Rank Novato', desc: 'Ignora os Requisitos, exceto outras Vantagens.' },
            { cost: 3, name: 'Rank Experiente', desc: '1 ponto a mais.' },
            { cost: 4, name: 'Rank Veterano', desc: '2 pontos a mais.' },
            { cost: 5, name: 'Rank Heróico', desc: '3 pontos a mais.' }
        ]},
        { id: 'rap_darkvis', name: 'Visão No Escuro', cost: 1, type: 'checkbox', desc: 'O ser ignora penalidades por Penumbra e Escuridão (mas não por Escuro Como um Breu).' },
        { id: 'rap_fly', name: 'Voo', cost: 2, type: 'upgrade', desc: 'Pode voar pelos ares.', levels: [
            { cost: 2, name: 'Básica', desc: 'A espécie pode voar com Movimentação 6.' },
            { cost: 4, name: 'Rápida', desc: 'Pode voar com Movimentação 12.' },
            { cost: 6, name: 'Velocidade Extrema', desc: 'A criatura pode voar com Movimentação 24 e "correr" por mais 2d6.' }
        ]}
    ],
    racialAbilitiesNeg: [
        { id: 'ran_lowparry', name: 'Aparar Baixo', cost: -1, max: 3, type: 'stack', desc: 'Estes seres são péssimos se defendendo em combate corpo a corpo; Aparar -1.' },
        { id: 'ran_mind_hind', name: 'Complicação', cost: 0, type: 'multiItem', max: 5, requireInput: 'hindrance', desc: 'A raça tem uma complicação inerente. O custo se adapta à complicação (-1 p/ Menor e -2 p/ Maior).' },
        { id: 'ran_dependency', name: 'Dependência', cost: -2, max: 1, type: 'multiItem', requireInput: 'text', desc: 'A criatura deve consumir ou ter contato com algum tipo de substância relativamente comum por uma hora a cada 24 horas.' },
        { id: 'ran_fragile', name: 'Frágil', cost: -1, max: 2, type: 'stack', desc: 'A criatura é menos resistente do que a maioria. Reduza sua Resistência em 1.' },
        { id: 'ran_weakenv', name: 'Fraqueza Ambiental', cost: -1, type: 'multiItem', max: 5, requireInput: 'text', desc: 'A raça sofre uma penalidade de -4 para resistir a um efeito ambiental específico, tais como calor, frio etc. Se sofrer ataque baseado na forma, é bônus de dano.' },
        { id: 'ran_racenemy', name: 'Inimigo Racial', cost: -1, type: 'multiItem', max: 5, requireInput: 'text', desc: 'A espécie não gosta de outra espécie relativamente comum. Penalidade de -2 em rolagens de Persuadir.' },
        { id: 'ran_lowpace', name: 'Movimentação Reduzida', cost: -1, type: 'upgrade', desc: 'Deformidade ou pernas curtas.', levels: [
            { cost: -1, name: 'Movimentação -1', desc: 'Reduza 1 quadro da sua Movimentação andando e seu dado de corrida em um tipo.' },
            { cost: -2, name: 'Movimentação -2', desc: 'Reduza a Movimentação em outros 2 pontos e subtraia 2 de rolagens de Atletismo.' }
        ]},
        { id: 'ran_mute', name: 'Não Fala', cost: -1, type: 'checkbox', desc: 'A raça não tem cordas vocais ou por qualquer outro motivo não pode formar os sons comuns feitos pela maioria das raças.' },
        { id: 'ran_attrpen', name: 'Penalidade em Atributo', cost: -2, type: 'multiItem', max: 5, requireInput: 'select', options: ['Agilidade', 'Astúcia', 'Espírito', 'Força', 'Vigor'], desc: 'Diminuição de Atributo (mas não suas perícias).', levels: [
            { cost: -2, name: 'Penalidade de -1', desc: 'Sofre uma penalidade de -1.' },
            { cost: -3, name: 'Penalidade de -2', desc: 'Sofre uma penalidade de -2.' }
        ]},
        { id: 'ran_skillpen', name: 'Penalidade em Perícia', cost: -1, type: 'multiItem', max: 10, requireInput: 'text', desc: 'A raça sofre uma penalidade para uma perícia especifica.', levels: [
            { cost: -1, name: 'Perícia -1 (Comum)', desc: 'Penalidade de -1 para uma perícia muito comum.' },
            { cost: -2, name: 'Perícia -2', desc: 'Penalidade de -2 para perícia comum ou -2 para perícia incomum.' },
            { cost: -4, name: 'Perícia -4 (Incomum)', desc: 'Penalidade de -4 para perícias pouco usadas.' }
        ]},
        { id: 'ran_lesscoreskill', name: 'Perícias Básicas Reduzidas', cost: -1, type: 'multiItem', max: 5, requireInput: 'select', options: ['Atletismo', 'Conhecimento', 'Furtividade', 'Perceber', 'Persuadir'], desc: 'A raça começa com uma perícia básica a menos. A perícia pode ser adquirida normalmente, mas não começa o jogo com um d4.' },
        { id: 'ran_sizedown', name: 'Tamanho -1', cost: -1, type: 'checkbox', desc: 'A entidade é menor que o normal, reduzindo seu Tamanho e Resistência em 1.' },
        { id: 'ran_bulky', name: 'Volumoso', cost: -2, type: 'checkbox', desc: 'A raça é particularmente grande. Ele subtrai 2 de rolagens de Característica quando usa equipamento que não foi especificamente projetado para sua raça.' }
    ]
};



